#!/usr/bin/env python3
"""DCS 404 — Notebook generator. Run: python generate_notebooks.py"""
import json, os, uuid

OUT = "notebooks"
os.makedirs(OUT, exist_ok=True)

def nb(cells):
    return {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py", "mimetype": "text/x-python",
                "name": "python", "pygments_lexer": "ipython3", "version": "3.9.0"
            }
        },
        "cells": cells
    }

def md(s):
    return {"cell_type": "markdown", "id": uuid.uuid4().hex[:8], "metadata": {}, "source": s}

def code(s):
    return {"cell_type": "code", "id": uuid.uuid4().hex[:8], "metadata": {},
            "execution_count": None, "outputs": [], "source": s}

def save(name, cells):
    path = os.path.join(OUT, name)
    with open(path, "w") as f:
        json.dump(nb(cells), f, indent=1)
    print(f"  Created: {path}")

# ===========================================================================
# 01 — AI FUNDAMENTALS, SEARCH, AND GAMES
# ===========================================================================
save("01_ai_fundamentals.ipynb", [
    md("# Notebook 1: AI Fundamentals, Search Techniques, and Games\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Explain what AI is and name its major subfields\n- Implement BFS and DFS from scratch\n- Understand heuristic-based search (A*)\n- Build a Minimax-powered Tic-Tac-Toe AI\n- Explain why Alpha-Beta pruning speeds up Minimax"),
    md("## 1. What Is Artificial Intelligence?\n\nAI is the science of building systems that perceive their environment and take actions that maximise their chance of achieving goals.\n\n### Brief history\n| Year | Milestone |\n|------|-----------|\n| 1950 | Turing publishes *Computing Machinery and Intelligence* |\n| 1956 | Dartmouth Conference — \"AI\" coined |\n| 1997 | Deep Blue defeats Kasparov at chess |\n| 2012 | AlexNet wins ImageNet → deep-learning era |\n| 2022+ | Large language models (GPT-4, Claude, Gemini) |\n\n### Major subfields\n- **Search & Planning** — finding sequences of actions\n- **Machine Learning** — learning from data\n- **Natural Language Processing** — understanding text/speech\n- **Computer Vision** — interpreting images\n- **Robotics** — acting in the physical world"),
    code("# A simple reflex agent for a two-room vacuum world\nclass VacuumAgent:\n    def act(self, location, status):\n        if status == 'Dirty':\n            return 'Suck'\n        return 'Move Right' if location == 'A' else 'Move Left'\n\nagent = VacuumAgent()\nscenarios = [('A','Dirty'),('A','Clean'),('B','Dirty'),('B','Clean')]\nfor loc, stat in scenarios:\n    print(f'  Location={loc}, Status={stat}  →  {agent.act(loc, stat)}')"),
    md("## 2. Problem Solving as Search\n\nMany AI problems can be framed as **graph search**:\n\n| Component | Meaning |\n|-----------|---------|\n| **State** | Snapshot of the world |\n| **Initial state** | Where we start |\n| **Goal state** | Where we want to be |\n| **Actions** | Legal moves from a state |\n| **Transition model** | New state after an action |\n| **Path cost** | Total cost of a solution path |"),
    code("# A small undirected graph we will search\ngraph = {\n    'A': ['B', 'C'],\n    'B': ['A', 'D', 'E'],\n    'C': ['A', 'F'],\n    'D': ['B'],\n    'E': ['B', 'F'],\n    'F': ['C', 'E', 'G'],\n    'G': ['F']\n}\nprint('Nodes:', list(graph.keys()))\nprint('Edges from A:', graph['A'])"),
    md("## 3. Breadth-First Search vs Depth-First Search\n\n| Property | BFS | DFS |\n|----------|-----|-----|\n| Completeness | ✅ | ❌ (may loop) |\n| Optimality (unweighted) | ✅ | ❌ |\n| Time | O(b^d) | O(b^m) |\n| Space | O(b^d) | O(bm) |\n\n*b = branching factor, d = solution depth, m = max depth*"),
    code("from collections import deque\n\ndef bfs(graph, start, goal):\n    queue = deque([[start]])\n    visited = {start}\n    while queue:\n        path = queue.popleft()\n        node = path[-1]\n        if node == goal:\n            return path\n        for nbr in graph[node]:\n            if nbr not in visited:\n                visited.add(nbr)\n                queue.append(path + [nbr])\n    return None\n\ndef dfs(graph, start, goal, path=None, visited=None):\n    path = path or [start]\n    visited = visited or {start}\n    if start == goal:\n        return path\n    for nbr in graph[start]:\n        if nbr not in visited:\n            visited.add(nbr)\n            result = dfs(graph, nbr, goal, path + [nbr], visited)\n            if result:\n                return result\n    return None\n\nbfs_path = bfs(graph, 'A', 'G')\ndfs_path = dfs(graph, 'A', 'G')\nprint(f'BFS: {\" → \".join(bfs_path)}  (steps={len(bfs_path)-1})')\nprint(f'DFS: {\" → \".join(dfs_path)}  (steps={len(dfs_path)-1})')"),
    code("import matplotlib.pyplot as plt\ntry:\n    import networkx as nx\n    G = nx.Graph(graph)\n    pos = nx.spring_layout(G, seed=42)\n    fig, axes = plt.subplots(1, 2, figsize=(13, 4))\n    for ax, path, title in zip(axes, [bfs_path, dfs_path], ['BFS', 'DFS']):\n        edges = [(path[i], path[i+1]) for i in range(len(path)-1)]\n        nx.draw_networkx(G, pos, ax=ax, node_color='#AED6F1', node_size=700, font_size=11)\n        nx.draw_networkx_edges(G, pos, edgelist=edges, ax=ax, edge_color='crimson', width=3)\n        nx.draw_networkx_nodes(G, pos, nodelist=path, ax=ax, node_color='#F1948A', node_size=700)\n        ax.set_title(f'{title}: {\" → \".join(path)}')\n        ax.axis('off')\n    plt.tight_layout(); plt.show()\nexcept ImportError:\n    print('Install networkx for the visualisation: pip install networkx')\n    print(f'BFS path: {bfs_path}')\n    print(f'DFS path: {dfs_path}')"),
    md("## 4. Informed Search — A*\n\n$$f(n) = g(n) + h(n)$$\n\n- $g(n)$ — actual cost from start to $n$\n- $h(n)$ — heuristic estimate from $n$ to goal\n- $f(n)$ — estimated total path cost\n\nA* is optimal as long as $h$ is **admissible** (never overestimates) and **consistent**."),
    code("import heapq\n\ndef astar(wgraph, h, start, goal):\n    # (f, g, node, path)\n    pq = [(h.get(start,0), 0, start, [start])]\n    best_g = {}\n    while pq:\n        f, g, node, path = heapq.heappop(pq)\n        if node in best_g and best_g[node] <= g:\n            continue\n        best_g[node] = g\n        if node == goal:\n            return path, g\n        for nbr, cost in wgraph.get(node, {}).items():\n            ng = g + cost\n            nf = ng + h.get(nbr, 0)\n            heapq.heappush(pq, (nf, ng, nbr, path + [nbr]))\n    return None, float('inf')\n\nwgraph = {\n    'A': {'B':1,'C':4}, 'B': {'A':1,'D':3,'E':2},\n    'C': {'A':4,'F':5}, 'D': {'B':3},\n    'E': {'B':2,'F':1}, 'F': {'C':5,'E':1,'G':2}, 'G': {}\n}\nh = {'A':7,'B':5,'C':6,'D':6,'E':3,'F':2,'G':0}\n\npath, cost = astar(wgraph, h, 'A', 'G')\nprint(f'A* path : {\" → \".join(path)}')\nprint(f'Total cost: {cost}')"),
    md("## 5. Minimax for Games\n\nIn a two-player zero-sum game:\n- **MAX** player (you) tries to *maximise* the score\n- **MIN** player (opponent) tries to *minimise* your score\n\nBoth players are assumed to play **optimally**."),
    code("# Perfect Tic-Tac-Toe AI via Minimax\n# Board: list of 9 ints  (0=empty, 1=X, -1=O)\n\nWINS = [(0,1,2),(3,4,5),(6,7,8),(0,3,6),(1,4,7),(2,5,8),(0,4,8),(2,4,6)]\n\ndef winner(b):\n    for a,c,d in WINS:\n        if b[a]==b[c]==b[d]!=0:\n            return b[a]\n    return 0 if 0 not in b else None\n\ndef minimax(b, maximising):\n    w = winner(b)\n    if w is not None:\n        return w\n    scores = []\n    for i in range(9):\n        if b[i] == 0:\n            b[i] = 1 if maximising else -1\n            scores.append(minimax(b, not maximising))\n            b[i] = 0\n    return max(scores) if maximising else min(scores)\n\ndef best_move(b):\n    return max((i for i in range(9) if b[i]==0),\n               key=lambda i: (b.__setitem__(i,1), minimax(b,False), b.__setitem__(i,0)) or minimax(b[:i]+[1]+b[i+1:], False))\n\n# Cleaner best_move\ndef best_move(b):\n    best_s, best_i = -float('inf'), -1\n    for i in range(9):\n        if b[i] == 0:\n            b[i] = 1\n            s = minimax(b, False)\n            b[i] = 0\n            if s > best_s:\n                best_s, best_i = s, i\n    return best_i\n\ndef show(b):\n    sym = {1:'X',-1:'O',0:'.'}\n    for r in range(3):\n        print(' '.join(sym[b[r*3+c]] for c in range(3)))\n    print()\n\nboard = [1,0,-1, 0,1,0, 0,0,-1]\nprint('Current board:')\nshow(board)\nmv = best_move(board)\nboard[mv] = 1\nprint(f'AI (X) plays at index {mv}:')\nshow(board)\nw = winner(board)\nprint('Result:', {1:'X wins!', -1:'O wins!', 0:'Draw'}.get(w,'Game on'))"),
    md("## 6. Alpha-Beta Pruning\n\nMinimax is correct but slow. Alpha-Beta pruning **skips branches that cannot affect the result**:\n\n- **α** — best score MAX is guaranteed so far\n- **β** — best score MIN is guaranteed so far\n- Prune when **α ≥ β**\n\nSame result as Minimax but typically **O(b^(d/2))** instead of **O(b^d)**."),
    code("nodes_visited = 0\n\ndef minimax_ab(b, maximising, alpha=-float('inf'), beta=float('inf')):\n    global nodes_visited\n    nodes_visited += 1\n    w = winner(b)\n    if w is not None:\n        return w\n    for i in range(9):\n        if b[i] == 0:\n            b[i] = 1 if maximising else -1\n            score = minimax_ab(b, not maximising, alpha, beta)\n            b[i] = 0\n            if maximising:\n                alpha = max(alpha, score)\n            else:\n                beta = min(beta, score)\n            if alpha >= beta:\n                break  # prune remaining siblings\n    return alpha if maximising else beta\n\n# Count nodes for plain minimax\nboard_empty = [0]*9\nnodes_visited = 0\nminimax(board_empty, True)\nprint(f'Plain Minimax nodes evaluated  : ~{nodes_visited:,}')\n\nnodes_visited = 0\nminimax_ab(board_empty, True)\nprint(f'Alpha-Beta Pruning nodes evaluated: ~{nodes_visited:,}')"),
    md("## Exercises\n\n1. **Modify BFS** to also print the order in which nodes were visited. How does it differ from DFS?\n2. **Heuristic design**: For the 8-puzzle (3×3 sliding tiles), define an admissible heuristic and justify why it never overestimates.\n3. **Alpha-Beta depth**: If the game tree has branching factor `b=3` and depth `d=6`, how many nodes does plain Minimax visit? How many does Alpha-Beta visit in the best case?\n4. **Extend the AI**: Change the Tic-Tac-Toe AI so it plays as `O` (the minimising player). Play a game against it.\n\n## Reflection Questions\n\n- Why is BFS guaranteed to find the shortest path but DFS is not?\n- What does it mean for a heuristic to be *consistent* (monotone)?\n- Is an AI that plays perfect Tic-Tac-Toe \"intelligent\" in any meaningful sense?\n\n---\n**Next →** `02_numpy_essentials.ipynb`"),
])

# ===========================================================================
# 02 — NUMPY ESSENTIALS
# ===========================================================================
save("02_numpy_essentials.ipynb", [
    md("# Notebook 2: NumPy — The Computational Backbone\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Create and manipulate NumPy arrays\n- Understand dtype, shape, and reshaping\n- Apply vectorised operations and broadcasting\n- Use NumPy for basic linear algebra\n- Replace Python loops with fast array operations"),
    md("## 1. Why NumPy?\n\nPython lists are flexible but slow for numerical work because each element is a full Python object with overhead.\n\nNumPy stores elements in a **contiguous block of typed memory** — operations run in optimised C/Fortran under the hood.\n\n| Task | Python list | NumPy array |\n|------|-------------|-------------|\n| Sum 10 M numbers | ~0.5 s | ~0.01 s |\n| Element-wise multiply | requires loop | single expression |\n| Linear algebra | manual | built-in |\n\n> **Rule**: if you are writing a numeric loop in Python, there is almost certainly a NumPy one-liner for it."),
    code("import numpy as np\n\n# Creating arrays\na = np.array([1, 2, 3, 4, 5])\nb = np.array([[1,2,3],[4,5,6]], dtype=np.float32)\n\nprint('1-D array :', a)\nprint('Shape     :', a.shape)\nprint('2-D array :\\n', b)\nprint('Shape     :', b.shape, '  dtype:', b.dtype)\n\n# Factory functions\nprint('\\nzeros(3,4):\\n', np.zeros((3,4)))\nprint('arange(0,10,2):', np.arange(0,10,2))\nprint('linspace(0,1,5):', np.linspace(0,1,5))"),
    md("## 2. Indexing and Slicing\n\nNumPy slicing is just like Python slicing, but extended to multiple dimensions.\n\n```\narr[row_slice, col_slice]\n```\n\nBoolean indexing lets you filter rows by a condition."),
    code("m = np.arange(16).reshape(4, 4)\nprint('Matrix:\\n', m)\nprint('Row 1       :', m[1])\nprint('Col 2       :', m[:, 2])\nprint('Sub-matrix  :\\n', m[1:3, 1:3])\nprint('Top-right   :', m[0, -1])\n\n# Boolean indexing\nprint('Elements > 9:', m[m > 9])\n# Fancy indexing\nprint('Rows 0 and 3:\\n', m[[0, 3]])"),
    md("## 3. Vectorised Operations and Broadcasting\n\n**Vectorisation**: applying an operation to an entire array at once — no explicit loops.\n\n**Broadcasting**: NumPy automatically expands smaller arrays to match larger ones:\n\n```\n(4, 3) + (3,)  →  broadcasts (3,) to (4, 3) — adds to every row\n```"),
    code("import time\n\nN = 5_000_000\npython_list = list(range(N))\nnp_arr = np.arange(N, dtype=np.float64)\n\nt0 = time.time()\npython_result = [x**2 for x in python_list]\nprint(f'Python loop : {time.time()-t0:.3f}s')\n\nt0 = time.time()\nnp_result = np_arr ** 2\nprint(f'NumPy       : {time.time()-t0:.3f}s')\n\n# Broadcasting demo\nA = np.array([[1,2,3],[4,5,6],[7,8,9]])\nbias = np.array([10, 20, 30])\nprint('\\nA + bias (broadcasting):\\n', A + bias)"),
    md("## 4. Common NumPy Functions\n\nNumPy ships with hundreds of mathematical functions — all vectorised."),
    code("rng = np.random.default_rng(seed=42)\ndata = rng.normal(loc=50, scale=10, size=(100,))\n\nprint(f'Mean   : {np.mean(data):.2f}')\nprint(f'Std    : {np.std(data):.2f}')\nprint(f'Min    : {np.min(data):.2f}')\nprint(f'Max    : {np.max(data):.2f}')\nprint(f'Median : {np.median(data):.2f}')\nprint(f'25th % : {np.percentile(data, 25):.2f}')\n\n# Sorting and argsort\nsmall = np.array([3, 1, 4, 1, 5, 9, 2])\nprint('\\nSorted         :', np.sort(small))\nprint('Argsort indices:', np.argsort(small))\nprint('Top-3 values   :', small[np.argsort(small)[-3:]])"),
    md("## 5. Linear Algebra with NumPy\n\nLinear algebra is at the heart of machine learning — weights, activations, covariance matrices, and more."),
    code("A = np.array([[2., 1.], [5., 3.]])\nb_vec = np.array([8., 21.])\n\n# Matrix-vector multiply\nprint('A @ b :', A @ b_vec)\n\n# Solving Ax = b\nx = np.linalg.solve(A, b_vec)\nprint('Solution x:', x)\nprint('Verify Ax = b:', np.allclose(A @ x, b_vec))\n\n# Eigenvalues\neigenvalues, eigenvectors = np.linalg.eig(A)\nprint('\\nEigenvalues:', eigenvalues)\n\n# SVD (used in PCA and dimensionality reduction)\nU, S, Vt = np.linalg.svd(A)\nprint('Singular values:', S)\n\n# Dot product vs element-wise\nv1 = np.array([1., 2., 3.])\nv2 = np.array([4., 5., 6.])\nprint('\\nDot product  :', np.dot(v1, v2))\nprint('Element-wise :', v1 * v2)"),
    md("## 6. Reshaping and Stacking"),
    code("arr = np.arange(24)\nprint('Original  :', arr.shape)\nprint('(2,3,4)   :\\n', arr.reshape(2,3,4))\nprint('(6,4)     :\\n', arr.reshape(6,4))\nprint('Flatten   :', arr.reshape(4,6).flatten().shape)\n\n# Stacking\na = np.array([[1,2],[3,4]])\nb = np.array([[5,6],[7,8]])\nprint('\\nvstack:\\n', np.vstack([a,b]))\nprint('hstack:\\n', np.hstack([a,b]))"),
    md("## Exercises\n\n1. Create a 5×5 identity matrix using `np.eye`. Then multiply it by 7 and verify the result.\n2. Generate 1 000 samples from a standard normal distribution. Compute the Z-scores: `z = (x - mean) / std`. Confirm the Z-scores have mean ≈ 0 and std ≈ 1.\n3. Without using a loop, compute the Euclidean distance between every pair of rows in a (4, 3) matrix. *Hint*: Broadcasting.\n4. Given a 2D array of exam scores (shape `(30, 5)`), find the student (row) with the highest average score.\n\n## Reflection Questions\n- Why does NumPy store data in a contiguous memory block? What advantage does that give over Python lists?\n- What happens when you slice a NumPy array — do you get a copy or a view? Why does this matter?\n\n---\n**Next →** `03_pandas_essentials.ipynb`"),
])

# ===========================================================================
# 03 — PANDAS ESSENTIALS
# ===========================================================================
save("03_pandas_essentials.ipynb", [
    md("# Notebook 3: Pandas — Data Wrangling Essentials\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Understand Series and DataFrame structures\n- Load, inspect, and clean tabular data\n- Filter, group, and aggregate data\n- Merge and reshape DataFrames\n- Apply lambda functions and custom transformations"),
    md("## 1. Series and DataFrame\n\n- A **Series** is a 1-D labelled array (like a column in a spreadsheet)\n- A **DataFrame** is a 2-D table of Series (the spreadsheet itself)\n\nEach axis has an **index** — labels that let you access data by name rather than integer position."),
    code("import pandas as pd\nimport numpy as np\n\n# Series\ntemps = pd.Series([22.5, 19.0, 24.3, 21.8, 17.2],\n                  index=['Mon','Tue','Wed','Thu','Fri'],\n                  name='Temperature (°C)')\nprint(temps)\nprint(f'\\nMean temp: {temps.mean():.1f}°C')\nprint(f'Hottest day: {temps.idxmax()}')\n\n# DataFrame from dict\ndata = {\n    'Name'  : ['Alice','Bob','Carol','Dave','Eve'],\n    'Age'   : [22, 25, 23, 28, 21],\n    'Score' : [87.5, 91.0, 78.3, 95.1, 82.0],\n    'Grade' : ['B','A','C','A','B'],\n}\ndf = pd.DataFrame(data)\nprint('\\n', df)"),
    md("## 2. Inspecting Data\n\nAlways start an analysis with a quick inspection."),
    code("# Use the built-in Titanic dataset via seaborn or a small synthetic one\nimport io\ncsv_data = '''PassengerId,Survived,Pclass,Name,Sex,Age,Fare\n1,0,3,Braund,male,22,7.25\n2,1,1,Cumings,female,38,71.28\n3,1,3,Heikkinen,female,26,7.92\n4,1,1,Futrelle,female,35,53.10\n5,0,3,Allen,male,35,8.05\n6,0,3,Moran,male,,8.46\n7,0,1,McCarthy,male,54,51.86\n8,0,3,Palsson,male,2,21.08\n9,1,3,Johnson,female,27,11.13\n10,1,2,Nasser,female,14,30.07\n'''\ndf_t = pd.read_csv(io.StringIO(csv_data))\n\nprint('Shape       :', df_t.shape)\nprint('\\nColumn types:\\n', df_t.dtypes)\nprint('\\nFirst 3 rows:\\n', df_t.head(3))\nprint('\\nBasic stats:\\n', df_t.describe())"),
    md("## 3. Selecting and Filtering Data"),
    code("# Select columns\nprint(df_t[['Name','Survived','Pclass']])\n\n# Boolean filter\nfirst_class = df_t[df_t['Pclass'] == 1]\nprint(f'\\n1st class passengers: {len(first_class)}')\n\nsurvivors_female = df_t[(df_t['Survived']==1) & (df_t['Sex']=='female')]\nprint(f'Female survivors: {len(survivors_female)}')\n\n# .loc vs .iloc\nprint('\\nRow by label (loc 2:4):\\n', df_t.loc[2:4, ['Name','Age']])\nprint('\\nRow by position (iloc 0:3, cols 0-2):\\n', df_t.iloc[0:3, 0:3])"),
    md("## 4. Handling Missing Data"),
    code("print('Missing values per column:\\n', df_t.isnull().sum())\nprint(f'\\n% missing Age: {df_t[\"Age\"].isnull().mean()*100:.1f}%')\n\n# Fill missing age with median\ndf_t['Age_filled'] = df_t['Age'].fillna(df_t['Age'].median())\n\n# Drop rows with any missing value\ndf_dropped = df_t.dropna()\nprint(f'Rows before drop: {len(df_t)}, after: {len(df_dropped)}')\n\n# Detect duplicates\nprint(f'Duplicate rows: {df_t.duplicated().sum()}')"),
    md("## 5. GroupBy and Aggregation"),
    code("# Survival rate by class\nprint('Survival rate by Pclass:')\nprint(df_t.groupby('Pclass')['Survived'].mean().round(2))\n\n# Multiple aggregations\nprint('\\nAge stats by Sex:')\nprint(df_t.groupby('Sex')['Age'].agg(['mean','median','count']).round(1))\n\n# Pivot table\npivot = df_t.pivot_table(values='Fare', index='Pclass', columns='Sex', aggfunc='mean')\nprint('\\nAverage Fare (Pclass × Sex):\\n', pivot.round(1))"),
    md("## 6. Applying Functions and Creating New Columns"),
    code("# Vectorised operations\ndf_t['Fare_log'] = np.log1p(df_t['Fare'])\n\n# Apply with lambda\ndf_t['Age_group'] = df_t['Age_filled'].apply(\n    lambda a: 'Child' if a < 16 else ('Young' if a < 35 else 'Adult'))\n\nprint(df_t[['Name','Age_filled','Age_group','Fare_log']].head())\n\n# Value counts\nprint('\\nAge groups:\\n', df_t['Age_group'].value_counts())"),
    md("## 7. Merging and Reshaping"),
    code("# Merge (like SQL JOIN)\nleft = pd.DataFrame({'id':[1,2,3], 'name':['Alice','Bob','Carol']})\nright = pd.DataFrame({'id':[1,2,4], 'score':[90,85,78]})\n\nprint('Inner join:')\nprint(pd.merge(left, right, on='id', how='inner'))\nprint('\\nLeft join:')\nprint(pd.merge(left, right, on='id', how='left'))\n\n# Melt (wide → long)\nwide = pd.DataFrame({'student':['Alice','Bob'],\n                     'math':[90,80], 'english':[85,88]})\nlong = pd.melt(wide, id_vars='student', var_name='subject', value_name='score')\nprint('\\nMelted (wide → long):\\n', long)"),
    md("## Exercises\n\n1. Using the titanic mini-dataset, compute the overall survival rate. Then break it down by `Sex` **and** `Pclass` together using `groupby`.\n2. Add a column `'Fare_category'` that labels fares as `'Low'` (< 10), `'Medium'` (10–50), or `'High'` (> 50).\n3. Sort the DataFrame by `Fare` descending and reset the index. Which passenger paid the most?\n4. Load any CSV file of your choice with `pd.read_csv()`. Identify columns with > 30% missing values and drop them.\n\n## Reflection Questions\n- What is the difference between `.loc` and `.iloc`?\n- When would you use `melt` vs `pivot_table`?\n- Why is `groupby` often faster than writing an explicit loop?\n\n---\n**Next →** `04_data_visualization.ipynb`"),
])

# ===========================================================================
# 04 — DATA VISUALIZATION
# ===========================================================================
save("04_data_visualization.ipynb", [
    md("# Notebook 4: Data Visualization with Matplotlib\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Create and customise line, scatter, bar, and histogram plots\n- Build multi-panel figures with subplots\n- Visualise distributions and relationships\n- Add titles, labels, legends, and annotations\n- Choose the right chart type for each situation"),
    code("import numpy as np\nimport matplotlib.pyplot as plt\nimport pandas as pd\n\n# Reproducibility\nnp.random.seed(42)\n\n# Pretty defaults\nplt.rcParams.update({\n    'figure.dpi': 100,\n    'axes.spines.top': False,\n    'axes.spines.right': False,\n    'font.size': 11,\n})"),
    md("## 1. Line Plot — Trends Over Time"),
    code("months = np.arange(1, 13)\nrevenue = [42, 38, 55, 61, 70, 66, 74, 80, 77, 85, 91, 105]\ncost    = [30, 32, 35, 38, 40, 41, 43, 45, 44, 47, 50, 55]\n\nfig, ax = plt.subplots(figsize=(10, 4))\nax.plot(months, revenue, marker='o', label='Revenue ($k)', color='steelblue', linewidth=2)\nax.plot(months, cost, marker='s', linestyle='--', label='Cost ($k)', color='tomato', linewidth=2)\nax.fill_between(months, cost, revenue, alpha=0.1, color='green', label='Profit margin')\nax.set_title('Monthly Revenue vs Cost')\nax.set_xlabel('Month')\nax.set_ylabel('Amount ($k)')\nax.set_xticks(months)\nax.legend()\nplt.tight_layout()\nplt.show()"),
    md("## 2. Scatter Plot — Relationships Between Variables"),
    code("n = 120\nheight = np.random.normal(170, 10, n)\nweight = 0.55 * height - 20 + np.random.normal(0, 5, n)\ngender = np.random.choice(['Male','Female'], n)\n\ncolors = ['#3498DB' if g=='Male' else '#E91E63' for g in gender]\n\nfig, ax = plt.subplots(figsize=(7, 5))\nscatter = ax.scatter(height, weight, c=colors, alpha=0.7, edgecolors='white', s=60)\nax.set_xlabel('Height (cm)')\nax.set_ylabel('Weight (kg)')\nax.set_title('Height vs Weight')\n\nfrom matplotlib.patches import Patch\nlegend_elements = [Patch(color='#3498DB', label='Male'),\n                   Patch(color='#E91E63', label='Female')]\nax.legend(handles=legend_elements)\n\n# Add regression line\ncoeffs = np.polyfit(height, weight, 1)\nx_line = np.linspace(height.min(), height.max(), 100)\nax.plot(x_line, np.polyval(coeffs, x_line), 'k--', alpha=0.5, label='Trend')\nplt.tight_layout()\nplt.show()"),
    md("## 3. Bar and Horizontal Bar Charts — Comparisons"),
    code("categories = ['Python','JavaScript','Java','C++','R','Go']\ncounts = [55, 47, 35, 28, 18, 12]\n\nfig, axes = plt.subplots(1, 2, figsize=(13, 4))\n\n# Vertical bar\nbar_colors = plt.cm.Blues(np.linspace(0.4, 0.9, len(categories)))\naxes[0].bar(categories, counts, color=bar_colors, edgecolor='white')\naxes[0].set_title('Popularity by Language (vertical)')\naxes[0].set_ylabel('Survey respondents (%)')\nfor i, v in enumerate(counts):\n    axes[0].text(i, v+0.5, str(v), ha='center', fontweight='bold')\n\n# Horizontal bar — better for long labels\nsorting = np.argsort(counts)\naxes[1].barh([categories[i] for i in sorting], [counts[i] for i in sorting],\n             color=bar_colors)\naxes[1].set_title('Popularity by Language (horizontal)')\naxes[1].set_xlabel('Survey respondents (%)')\nplt.tight_layout()\nplt.show()"),
    md("## 4. Histogram and Density Plot — Distributions"),
    code("scores = np.concatenate([\n    np.random.normal(65, 8, 80),\n    np.random.normal(85, 5, 40)\n])\n\nfig, axes = plt.subplots(1, 2, figsize=(13, 4))\n\n# Histogram\naxes[0].hist(scores, bins=20, color='steelblue', edgecolor='white', alpha=0.8)\naxes[0].axvline(np.mean(scores), color='red', linestyle='--', label=f'Mean={np.mean(scores):.1f}')\naxes[0].axvline(np.median(scores), color='orange', linestyle='--', label=f'Median={np.median(scores):.1f}')\naxes[0].set_xlabel('Score')\naxes[0].set_ylabel('Count')\naxes[0].set_title('Score Distribution')\naxes[0].legend()\n\n# Box plot\ngroup_a = np.random.normal(70, 10, 50)\ngroup_b = np.random.normal(80, 6, 50)\ngroup_c = np.random.normal(75, 12, 50)\naxes[1].boxplot([group_a, group_b, group_c],\n                labels=['Group A','Group B','Group C'],\n                patch_artist=True,\n                boxprops=dict(facecolor='steelblue', alpha=0.5))\naxes[1].set_title('Score Distribution by Group')\naxes[1].set_ylabel('Score')\nplt.tight_layout()\nplt.show()"),
    md("## 5. Heatmap — Correlation Matrix"),
    code("# Generate a correlation-like matrix\nnp.random.seed(0)\nraw = np.random.randn(100, 5)\ncols = ['Age','Income','Score','Experience','Satisfaction']\ndf = pd.DataFrame(raw, columns=cols)\ncorr = df.corr()\n\nfig, ax = plt.subplots(figsize=(6, 5))\nim = ax.imshow(corr, cmap='coolwarm', vmin=-1, vmax=1)\nplt.colorbar(im, ax=ax)\nax.set_xticks(range(len(cols))); ax.set_xticklabels(cols, rotation=45, ha='right')\nax.set_yticks(range(len(cols))); ax.set_yticklabels(cols)\nfor i in range(len(cols)):\n    for j in range(len(cols)):\n        ax.text(j, i, f'{corr.iloc[i,j]:.2f}', ha='center', va='center', fontsize=9)\nax.set_title('Correlation Matrix')\nplt.tight_layout()\nplt.show()"),
    md("## 6. The Anatomy of a Good Plot\n\nA well-designed plot has:\n1. **Title** — what the chart shows\n2. **Axis labels with units** — never leave an axis unlabelled\n3. **Legend** — if multiple series\n4. **Appropriate scale** — start y-axis at 0 for bar charts\n5. **Minimal chartjunk** — remove gridlines and borders that do not add information\n6. **Accessible colours** — colour-blind friendly palettes (e.g., `viridis`, `tab10`)"),
    code("# Demonstrating good vs bad practices\nfig, axes = plt.subplots(1, 2, figsize=(13, 4))\nx = ['Q1','Q2','Q3','Q4']\ny = [100, 102, 104, 103]\n\n# 'Bad' chart — truncated y axis exaggerates small differences\naxes[0].bar(x, y, color='gray')\naxes[0].set_ylim(98, 106)\naxes[0].set_title('Misleading: y-axis starts at 98')\naxes[0].set_ylabel('Sales')\n\n# 'Good' chart — zero baseline\naxes[1].bar(x, y, color='steelblue')\naxes[1].set_ylim(0, 120)\naxes[1].set_title('Honest: y-axis starts at 0')\naxes[1].set_ylabel('Sales')\n\nplt.tight_layout()\nplt.show()\nprint('Same data — very different impression!')"),
    md("## Exercises\n\n1. Load the **iris dataset** (`from sklearn.datasets import load_iris`) and create a scatter matrix (pair plot) of the four features, coloured by species.\n2. Plot a **sine and cosine wave** on the same axes from 0 to 4π. Add proper labels, a legend, and a vertical line at x = π.\n3. Create a **stacked bar chart** showing the composition of a dataset (you choose: e.g., energy mix by country).\n4. Generate a **violin plot** comparing score distributions across three groups. When would you choose a violin over a box plot?\n\n## Reflection Questions\n- What are three ways a chart can be misleading without using incorrect data?\n- When is a pie chart appropriate, and when should you avoid it?\n\n---\n**Next →** `05_data_preparation.ipynb`"),
])

# ===========================================================================
# 05 — DATA PREPARATION AND FEATURE ENGINEERING
# ===========================================================================
save("05_data_preparation.ipynb", [
    md("# Notebook 5: Data Preparation and Feature Engineering\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Handle missing values systematically\n- Detect and treat outliers\n- Encode categorical variables correctly\n- Scale numerical features\n- Engineer new features from existing ones\n- Build a reusable scikit-learn pipeline"),
    md("## 1. Why Data Preparation Matters\n\n> \"Data scientists spend 80% of their time cleaning data and 20% complaining about cleaning data.\"\n\nA model is only as good as the data it learns from. Dirty data → bad predictions, even with a perfect algorithm.\n\n### The Data Preparation Pipeline\n```\nRaw Data\n  ↓ Inspection & profiling\n  ↓ Handle missing values\n  ↓ Handle outliers\n  ↓ Encode categoricals\n  ↓ Scale / normalise\n  ↓ Feature engineering\nClean Feature Matrix\n```"),
    code("import numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom sklearn.preprocessing import (\n    StandardScaler, MinMaxScaler, LabelEncoder,\n    OneHotEncoder, OrdinalEncoder\n)\nfrom sklearn.impute import SimpleImputer, KNNImputer\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.compose import ColumnTransformer\n\nnp.random.seed(42)\n\n# Synthetic messy dataset\ndef make_messy_dataset(n=200):\n    df = pd.DataFrame({\n        'age'    : np.random.randint(18, 70, n).astype(float),\n        'income' : np.random.normal(50000, 15000, n),\n        'score'  : np.random.normal(70, 15, n),\n        'city'   : np.random.choice(['London','NYC','Paris','Berlin'], n),\n        'edu'    : np.random.choice(['High School','Bachelor','Master','PhD'], n),\n        'target' : np.random.randint(0, 2, n),\n    })\n    # Introduce missing values\n    df.loc[df.sample(20).index, 'age'] = np.nan\n    df.loc[df.sample(15).index, 'income'] = np.nan\n    df.loc[df.sample(5).index, 'city'] = np.nan\n    # Introduce outliers\n    df.loc[[0,1,2], 'income'] = [500000, -5000, 1000000]\n    return df\n\ndf = make_messy_dataset()\nprint(df.shape)\ndf.head()"),
    md("## 2. Inspecting and Profiling Data"),
    code("print('=== Data Profile ===')\nprint(f'Shape  : {df.shape}')\nprint(f'\\nMissing values:\\n{df.isnull().sum()}')\nprint(f'\\nMissing %:\\n{(df.isnull().mean()*100).round(1)}')\nprint(f'\\nDtypes:\\n{df.dtypes}')\n\nnumerical = df.select_dtypes(include=np.number).columns.tolist()\ncategorical = df.select_dtypes(exclude=np.number).columns.tolist()\nprint(f'\\nNumerical columns : {numerical}')\nprint(f'Categorical columns: {categorical}')"),
    md("## 3. Handling Missing Values\n\n### Strategies\n| Strategy | When to use |\n|----------|-------------|\n| **Drop rows** | Very few rows affected, data is plentiful |\n| **Drop columns** | > 50–70% of column is missing |\n| **Mean / median fill** | Numerical; median is robust to outliers |\n| **Mode fill** | Categorical |\n| **KNN imputation** | When missing values have patterns |\n| **Model-based** | Complex relationships between features |"),
    code("# Mean / median imputation\nimp_median = SimpleImputer(strategy='median')\nimp_mode   = SimpleImputer(strategy='most_frequent')\n\ndf_clean = df.copy()\ndf_clean[['age','income','score']] = imp_median.fit_transform(df_clean[['age','income','score']])\ndf_clean['city'] = imp_mode.fit_transform(df_clean[['city']]).ravel()\n\nprint('Missing values after imputation:')\nprint(df_clean.isnull().sum())\n\n# KNN imputation (uses neighbouring samples)\nknn_imp = KNNImputer(n_neighbors=5)\ndf_knn = df.copy()\ndf_knn[['age','income','score']] = knn_imp.fit_transform(df_knn[['age','income','score']])\nprint('\\nKNN imputed income sample:', df_knn['income'].head(3).values.round(0))"),
    md("## 4. Detecting and Treating Outliers\n\n### Methods\n- **Z-score**: flag values where |z| > 3\n- **IQR (Interquartile Range)**: flag values outside Q1 − 1.5×IQR and Q3 + 1.5×IQR\n- **Winsorisation**: cap at a percentile instead of removing"),
    code("income = df_clean['income']\n\n# Z-score method\nz_scores = (income - income.mean()) / income.std()\nprint(f'Outliers (|z|>3): {(np.abs(z_scores) > 3).sum()}')\n\n# IQR method\nQ1, Q3 = income.quantile(0.25), income.quantile(0.75)\nIQR = Q3 - Q1\nlower, upper = Q1 - 1.5*IQR, Q3 + 1.5*IQR\noutlier_mask = (income < lower) | (income > upper)\nprint(f'Outliers (IQR)  : {outlier_mask.sum()}')\nprint(f'Outlier values  : {income[outlier_mask].values}')\n\n# Winsorise (cap at 1st and 99th percentile)\ndf_clean['income_winsor'] = np.clip(df_clean['income'],\n                                     df_clean['income'].quantile(0.01),\n                                     df_clean['income'].quantile(0.99))\nprint(f'\\nIncome max before: {df_clean[\"income\"].max():,.0f}')\nprint(f'Income max after : {df_clean[\"income_winsor\"].max():,.0f}')"),
    md("## 5. Encoding Categorical Variables\n\n| Encoding | When |\n|----------|------|\n| **Label Encoding** | Ordinal categories (Low < Medium < High) |\n| **One-Hot Encoding** | Nominal categories (no order); watch dummy-variable trap |\n| **Target Encoding** | High-cardinality columns in advanced workflows |"),
    code("# One-Hot Encoding\ncity_ohe = pd.get_dummies(df_clean['city'], prefix='city', drop_first=True)\nprint('One-hot encoded cities:\\n', city_ohe.head())\n\n# Ordinal Encoding for education\nedu_order = [['High School','Bachelor','Master','PhD']]\nordenc = OrdinalEncoder(categories=edu_order)\ndf_clean['edu_enc'] = ordenc.fit_transform(df_clean[['edu']])\nprint('\\nEducation ordinal mapping:')\nfor level, enc in zip(edu_order[0], range(4)):\n    print(f'  {level} → {enc}')"),
    md("## 6. Feature Scaling\n\nMany algorithms (SVM, KNN, logistic regression, neural networks) are sensitive to feature scale.\n\n| Scaler | Formula | Best when |\n|--------|---------|----------|\n| **StandardScaler** | (x − μ) / σ | Features roughly normal |\n| **MinMaxScaler** | (x − min) / (max − min) | Bounded output needed [0,1] |\n| **RobustScaler** | (x − median) / IQR | Many outliers |"),
    code("from sklearn.preprocessing import RobustScaler\n\nfeat = df_clean[['age','income_winsor','score']]\n\nstd_scaled   = StandardScaler().fit_transform(feat)\nminmax_scaled = MinMaxScaler().fit_transform(feat)\nrobust_scaled = RobustScaler().fit_transform(feat)\n\nfig, axes = plt.subplots(1, 3, figsize=(14, 4))\nfor ax, data, title in zip(axes,\n    [std_scaled, minmax_scaled, robust_scaled],\n    ['Standard (z-score)', 'Min-Max [0,1]', 'Robust (median/IQR)']):\n    ax.boxplot(data, labels=['age','income','score'])\n    ax.set_title(title)\nplt.suptitle('Scaling Comparison')\nplt.tight_layout()\nplt.show()"),
    md("## 7. Feature Engineering\n\nCreating **new features** from existing ones often boosts model performance more than tuning hyperparameters."),
    code("df_fe = df_clean.copy()\n\n# Ratio feature\ndf_fe['income_per_age'] = df_fe['income_winsor'] / df_fe['age']\n\n# Binning\ndf_fe['age_group'] = pd.cut(df_fe['age'], bins=[0,25,40,60,100],\n                             labels=['Young','Mid','Senior','Elder'])\n\n# Log transform (reduces skewness)\ndf_fe['log_income'] = np.log1p(df_fe['income_winsor'])\n\n# Polynomial features\ndf_fe['score_sq'] = df_fe['score'] ** 2\ndf_fe['age_score'] = df_fe['age'] * df_fe['score']\n\nprint('New features:')\nprint(df_fe[['income_per_age','age_group','log_income','score_sq','age_score']].head())"),
    md("## 8. Building a scikit-learn Pipeline\n\nA `Pipeline` chains transformers and estimators — ensuring the same transformations are applied to train and test data consistently, preventing **data leakage**."),
    code("from sklearn.linear_model import LogisticRegression\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import accuracy_score\n\nX = df_clean[['age','income_winsor','score','city','edu_enc']]\ny = df_clean['target']\n\nX_ohe = pd.get_dummies(X, columns=['city'], drop_first=True)\nX_train, X_test, y_train, y_test = train_test_split(X_ohe, y, test_size=0.2, random_state=42)\n\nnum_cols = ['age','income_winsor','score','edu_enc']\nohe_cols = [c for c in X_ohe.columns if c.startswith('city')]\n\npre = ColumnTransformer([\n    ('num', StandardScaler(), num_cols),\n    ('ohe', 'passthrough',   ohe_cols),\n])\n\npipe = Pipeline([\n    ('preprocessor', pre),\n    ('model', LogisticRegression(max_iter=500)),\n])\n\npipe.fit(X_train, y_train)\npred = pipe.predict(X_test)\nprint(f'Pipeline accuracy: {accuracy_score(y_test, pred):.3f}')"),
    md("## Exercises\n\n1. Using the Titanic dataset (`seaborn.load_dataset('titanic')`), build a complete preprocessing pipeline: impute missing values, encode categoricals, scale numericals.\n2. Create a feature `title` extracted from the passenger's name (Mr, Mrs, Miss, etc.) and encode it.\n3. Compare model accuracy before and after feature engineering on any dataset.\n4. What happens if you scale training data and then fit a new scaler on test data separately? (Run the experiment and explain why this is wrong.)\n\n## Reflection Questions\n- What is **data leakage** and how does a `Pipeline` prevent it?\n- Why is `StandardScaler` inappropriate for features with heavy outliers?\n- Why should you use `drop_first=True` in one-hot encoding?\n\n---\n**Next →** `06_linear_regression.ipynb`"),
])

# ===========================================================================
# 06 — LINEAR REGRESSION AND REGULARIZATION
# ===========================================================================
save("06_linear_regression.ipynb", [
    md("# Notebook 6: Linear Regression and Regularization\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Derive the closed-form solution for simple linear regression\n- Understand the cost function and gradient descent\n- Implement multiple linear regression with scikit-learn\n- Apply Ridge (L2) and Lasso (L1) regularization\n- Understand the bias-variance trade-off"),
    md("## 1. Intuition: Fitting a Line\n\nGiven data points $(x_i, y_i)$, we want to find the line:\n\n$$\\hat{y} = w_0 + w_1 x$$\n\nthat minimises the **Mean Squared Error** (MSE):\n\n$$\\text{MSE} = \\frac{1}{n} \\sum_{i=1}^n (y_i - \\hat{y}_i)^2$$\n\nThe parameters $w_0$ (intercept) and $w_1$ (slope) have a **closed-form solution** (Ordinary Least Squares):  \n$$w_1 = \\frac{\\sum (x_i - \\bar{x})(y_i - \\bar{y})}{\\sum (x_i - \\bar{x})^2}, \\quad w_0 = \\bar{y} - w_1 \\bar{x}$$"),
    code("import numpy as np\nimport matplotlib.pyplot as plt\n\nnp.random.seed(0)\n\n# Generate synthetic data: house size → price\nsize = np.random.uniform(500, 3500, 80)\nprice = 50 + 0.15 * size + np.random.normal(0, 30, 80)  # $k\n\n# OLS closed form\nxm, ym = size.mean(), price.mean()\nw1 = np.sum((size - xm) * (price - ym)) / np.sum((size - xm)**2)\nw0 = ym - w1 * xm\nprint(f'OLS: price = {w0:.2f} + {w1:.4f} × size')\n\nx_line = np.linspace(size.min(), size.max(), 100)\ny_line = w0 + w1 * x_line\n\nfig, ax = plt.subplots(figsize=(8,5))\nax.scatter(size, price, alpha=0.6, label='Data')\nax.plot(x_line, y_line, 'r-', linewidth=2, label=f'y = {w0:.1f} + {w1:.4f}x')\nax.set_xlabel('Size (sq ft)')\nax.set_ylabel('Price ($k)')\nax.set_title('Simple Linear Regression')\nax.legend()\nplt.tight_layout()\nplt.show()"),
    md("## 2. Gradient Descent — Learning the Parameters Iteratively\n\nFor large datasets, computing the closed-form solution is expensive. **Gradient Descent** updates parameters incrementally:\n\n$$w \\leftarrow w - \\alpha \\frac{\\partial \\text{MSE}}{\\partial w}$$\n\nwhere $\\alpha$ is the **learning rate** — how big each step is."),
    code("def mse(y_true, y_pred):\n    return np.mean((y_true - y_pred)**2)\n\ndef gradient_descent(X, y, lr=1e-7, epochs=2000):\n    w0, w1 = 0.0, 0.0\n    n = len(y)\n    history = []\n    for _ in range(epochs):\n        y_pred = w0 + w1 * X\n        dw0 = -2/n * np.sum(y - y_pred)\n        dw1 = -2/n * np.sum((y - y_pred) * X)\n        w0 -= lr * dw0\n        w1 -= lr * dw1\n        history.append(mse(y, y_pred))\n    return w0, w1, history\n\nw0_gd, w1_gd, hist = gradient_descent(size, price)\nprint(f'GD: price = {w0_gd:.2f} + {w1_gd:.4f} × size')\nprint(f'OLS: price = {w0:.2f} + {w1:.4f} × size')\n\nfig, ax = plt.subplots(figsize=(8,4))\nax.plot(hist)\nax.set_xlabel('Epoch')\nax.set_ylabel('MSE')\nax.set_title('Loss Curve During Training')\nplt.tight_layout()\nplt.show()"),
    md("## 3. Multiple Linear Regression\n\nWith $p$ features:\n\n$$\\hat{y} = w_0 + w_1 x_1 + w_2 x_2 + \\cdots + w_p x_p$$\n\nIn matrix form:\n\n$$\\hat{\\mathbf{y}} = X \\mathbf{w}$$\n\nThis is exactly what `LinearRegression` in scikit-learn solves."),
    code("from sklearn.datasets import fetch_california_housing\nfrom sklearn.linear_model import LinearRegression\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import mean_squared_error, r2_score\nimport pandas as pd\n\nhousing = fetch_california_housing(as_frame=True)\nX, y = housing.data, housing.target  # target = median house value\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\nlr = LinearRegression()\nlr.fit(X_train, y_train)\ny_pred = lr.predict(X_test)\n\nrmse = np.sqrt(mean_squared_error(y_test, y_pred))\nprint(f'RMSE : {rmse:.3f}')\nprint(f'R²   : {r2_score(y_test, y_pred):.3f}')\n\n# Feature coefficients\ncoef_df = pd.DataFrame({'Feature': X.columns, 'Coefficient': lr.coef_})\ncoef_df = coef_df.sort_values('Coefficient', key=abs, ascending=False)\nprint('\\nTop feature coefficients:')\nprint(coef_df.head())"),
    code("# Residual analysis\nresiduals = y_test - y_pred\nfig, axes = plt.subplots(1, 2, figsize=(13, 4))\naxes[0].scatter(y_pred, residuals, alpha=0.4, s=10)\naxes[0].axhline(0, color='red', linestyle='--')\naxes[0].set_xlabel('Predicted')\naxes[0].set_ylabel('Residual')\naxes[0].set_title('Residual Plot')\n\naxes[1].hist(residuals, bins=40, edgecolor='white', color='steelblue')\naxes[1].set_title('Distribution of Residuals')\naxes[1].set_xlabel('Residual')\nplt.tight_layout()\nplt.show()"),
    md("## 4. The Bias-Variance Trade-off\n\n| | High Bias | High Variance |\n|--|-----------|---------------|\n| **Symptom** | Underfitting | Overfitting |\n| **Train error** | High | Low |\n| **Test error** | High | High |\n| **Model** | Too simple | Too complex |\n\n**Solution**: Regularization — add a penalty term to the loss function to discourage large weights.\n\n## 5. Ridge (L2) Regularization\n\n$$\\text{Loss} = \\text{MSE} + \\lambda \\sum_{j=1}^p w_j^2$$\n\nLarge $\\lambda$ → stronger regularization → smaller weights → simpler model."),
    code("from sklearn.linear_model import Ridge, Lasso, ElasticNet\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.pipeline import Pipeline\n\ndef eval_model(name, model, X_train, X_test, y_train, y_test):\n    pipe = Pipeline([('scaler', StandardScaler()), ('model', model)])\n    pipe.fit(X_train, y_train)\n    pred = pipe.predict(X_test)\n    print(f'{name:20s}  RMSE={np.sqrt(mean_squared_error(y_test, pred)):.3f}  R²={r2_score(y_test, pred):.3f}')\n\neval_model('LinearRegression',   LinearRegression(),       X_train, X_test, y_train, y_test)\neval_model('Ridge (α=0.1)',       Ridge(alpha=0.1),        X_train, X_test, y_train, y_test)\neval_model('Ridge (α=10)',        Ridge(alpha=10),         X_train, X_test, y_train, y_test)\neval_model('Ridge (α=100)',       Ridge(alpha=100),        X_train, X_test, y_train, y_test)\neval_model('Lasso (α=0.01)',      Lasso(alpha=0.01),       X_train, X_test, y_train, y_test)\neval_model('ElasticNet (α=0.1)',  ElasticNet(alpha=0.1),   X_train, X_test, y_train, y_test)"),
    md("## 6. Lasso (L1) — Built-in Feature Selection\n\n$$\\text{Loss} = \\text{MSE} + \\lambda \\sum_{j=1}^p |w_j|$$\n\nLasso drives some coefficients to **exactly zero**, effectively selecting features. This makes it useful for high-dimensional data."),
    code("alphas = [0.001, 0.01, 0.1, 1.0, 10.0]\ncoefficients = []\n\nfor a in alphas:\n    pipe = Pipeline([('scaler', StandardScaler()), ('model', Lasso(alpha=a, max_iter=5000))])\n    pipe.fit(X_train, y_train)\n    coefficients.append(pipe.named_steps['model'].coef_)\n\nfig, ax = plt.subplots(figsize=(10, 5))\nfor i, feat in enumerate(X.columns):\n    ax.plot(alphas, [c[i] for c in coefficients], marker='o', label=feat)\nax.set_xscale('log')\nax.axhline(0, color='black', linestyle='--', alpha=0.3)\nax.set_xlabel('α (regularization strength)')\nax.set_ylabel('Coefficient value')\nax.set_title('Lasso Coefficient Paths')\nax.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=8)\nplt.tight_layout()\nplt.show()\nprint('As α increases, more coefficients shrink to zero (feature selection)')"),
    md("## Exercises\n\n1. Implement the **closed-form OLS** solution for multiple linear regression using the matrix formula: `w = (XᵀX)⁻¹ Xᵀy`. Compare coefficients with scikit-learn.\n2. Use `RidgeCV` to find the best `alpha` via cross-validation on the California housing dataset.\n3. Create a polynomial regression model (degree 3) using `PolynomialFeatures`. Does it overfit? How does Ridge regularization help?\n4. Plot the **learning curve** (train vs validation error as training size increases). What does it tell you about bias and variance?\n\n## Reflection Questions\n- Why does L1 (Lasso) produce sparse coefficients while L2 (Ridge) does not? (Visualise the constraint regions.)\n- If you double all your features, what happens to the OLS solution? What happens to Ridge?\n- When would you prefer Lasso over Ridge?\n\n---\n**Next →** `07_logistic_regression.ipynb`"),
])

# ===========================================================================
# 07 — LOGISTIC REGRESSION
# ===========================================================================
save("07_logistic_regression.ipynb", [
    md("# Notebook 7: Logistic Regression\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Explain why linear regression fails for classification\n- Derive the logistic (sigmoid) function\n- Understand maximum likelihood estimation\n- Implement logistic regression for binary and multiclass problems\n- Evaluate classifiers with the right metrics"),
    md("## 1. Why Not Linear Regression for Classification?\n\nSuppose we want to predict whether an email is spam (1) or not (0).\n\nLinear regression can predict values outside [0, 1] — e.g., 1.7 or −0.3 — which make no sense as probabilities.\n\nWe need a model that outputs a value **between 0 and 1**."),
    code("import numpy as np\nimport matplotlib.pyplot as plt\nfrom sklearn.linear_model import LogisticRegression, LinearRegression\nfrom sklearn.datasets import load_breast_cancer, load_iris\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import (\n    accuracy_score, classification_report,\n    confusion_matrix, roc_curve, roc_auc_score\n)\nimport warnings; warnings.filterwarnings('ignore')\n\nnp.random.seed(42)\n\n# 1D example: study hours → pass/fail\nhours = np.array([0.5,1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,8,9,10])\npassed = np.array([0,0,0,0,0,0,1,0,1,1,1,1,1,1,1,1,1])\n\nlin_reg = LinearRegression().fit(hours.reshape(-1,1), passed)\nlog_reg = LogisticRegression().fit(hours.reshape(-1,1), passed)\n\nx_plot = np.linspace(0, 10, 200)\nfig, axes = plt.subplots(1, 2, figsize=(13, 4))\nfor ax, model, title, extra in zip(\n        axes,\n        [lin_reg, log_reg],\n        ['Linear Regression (bad for classification)', 'Logistic Regression (correct)'],\n        [True, False]):\n    ax.scatter(hours, passed, color='steelblue', zorder=5)\n    preds = model.predict(x_plot.reshape(-1,1))\n    ax.plot(x_plot, preds, 'r-', linewidth=2)\n    if extra:\n        ax.axhline(0, color='gray', linestyle='--')\n        ax.axhline(1, color='gray', linestyle='--')\n    ax.set_xlabel('Study hours')\n    ax.set_ylabel('P(pass)')\n    ax.set_title(title)\nplt.tight_layout()\nplt.show()"),
    md("## 2. The Sigmoid (Logistic) Function\n\nWe model the probability of class 1 as:\n\n$$P(y=1 | x) = \\sigma(z) = \\frac{1}{1 + e^{-z}}, \\quad z = w_0 + w_1 x_1 + \\cdots + w_p x_p$$\n\nProperties of $\\sigma$:\n- Output is always in (0, 1)\n- $\\sigma(0) = 0.5$ — the **decision boundary**\n- Smooth and differentiable (needed for gradient descent)"),
    code("z = np.linspace(-8, 8, 300)\nsigmoid = 1 / (1 + np.exp(-z))\n\nfig, ax = plt.subplots(figsize=(8, 4))\nax.plot(z, sigmoid, 'steelblue', linewidth=2)\nax.axhline(0.5, color='red', linestyle='--', label='Decision boundary (p=0.5)')\nax.axvline(0, color='gray', linestyle='--', alpha=0.5)\nax.fill_between(z, 0.5, sigmoid, where=sigmoid>0.5, alpha=0.1, color='green', label='Predict class 1')\nax.fill_between(z, sigmoid, 0.5, where=sigmoid<0.5, alpha=0.1, color='red', label='Predict class 0')\nax.set_xlabel('z (linear combination of features)')\nax.set_ylabel('σ(z) = P(y=1)')\nax.set_title('The Sigmoid Function')\nax.legend()\nplt.tight_layout()\nplt.show()"),
    md("## 3. The Loss Function: Binary Cross-Entropy\n\nWe maximise the likelihood (or equivalently minimise the **binary cross-entropy loss**):\n\n$$\\mathcal{L} = -\\frac{1}{n} \\sum_{i=1}^n \\left[ y_i \\log(\\hat{p}_i) + (1-y_i) \\log(1-\\hat{p}_i) \\right]$$\n\nIntuition:\n- When $y_i = 1$ and $\\hat{p}_i \\to 0$: $-\\log(0) = \\infty$ — large penalty\n- When $y_i = 1$ and $\\hat{p}_i \\to 1$: $-\\log(1) = 0$ — no penalty"),
    code("# Visualise the loss for y=1\np = np.linspace(0.001, 0.999, 300)\nloss_y1 = -np.log(p)\nloss_y0 = -np.log(1 - p)\n\nfig, ax = plt.subplots(figsize=(8, 4))\nax.plot(p, loss_y1, label='Loss when y=1 (penalise low predictions)', color='green')\nax.plot(p, loss_y0, label='Loss when y=0 (penalise high predictions)', color='red')\nax.set_xlabel('Predicted probability p̂')\nax.set_ylabel('Loss')\nax.set_title('Binary Cross-Entropy Loss')\nax.legend()\nax.set_ylim(0, 5)\nplt.tight_layout()\nplt.show()"),
    md("## 4. Binary Classification: Breast Cancer Dataset"),
    code("cancer = load_breast_cancer()\nX, y = cancer.data, cancer.target  # 0=malignant, 1=benign\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.pipeline import Pipeline\n\npipe = Pipeline([\n    ('scaler', StandardScaler()),\n    ('clf', LogisticRegression(max_iter=1000, C=1.0))\n])\npipe.fit(X_train, y_train)\ny_pred = pipe.predict(X_test)\ny_prob = pipe.predict_proba(X_test)[:, 1]\n\nprint(f'Accuracy: {accuracy_score(y_test, y_pred):.4f}')\nprint('\\nClassification Report:')\nprint(classification_report(y_test, y_pred, target_names=cancer.target_names))"),
    code("# Confusion matrix\ncm = confusion_matrix(y_test, y_pred)\nfig, axes = plt.subplots(1, 2, figsize=(13, 4))\n\nim = axes[0].imshow(cm, cmap='Blues')\naxes[0].set_xticks([0,1]); axes[0].set_xticklabels(cancer.target_names)\naxes[0].set_yticks([0,1]); axes[0].set_yticklabels(cancer.target_names)\naxes[0].set_xlabel('Predicted'); axes[0].set_ylabel('Actual')\naxes[0].set_title('Confusion Matrix')\nfor i in range(2):\n    for j in range(2):\n        axes[0].text(j, i, str(cm[i,j]), ha='center', va='center',\n                     color='white' if cm[i,j] > cm.max()/2 else 'black', fontsize=14)\n\n# ROC curve\nfpr, tpr, _ = roc_curve(y_test, y_prob)\nauc = roc_auc_score(y_test, y_prob)\naxes[1].plot(fpr, tpr, linewidth=2, label=f'AUC = {auc:.3f}')\naxes[1].plot([0,1],[0,1], 'k--', alpha=0.5, label='Random classifier')\naxes[1].set_xlabel('False Positive Rate')\naxes[1].set_ylabel('True Positive Rate')\naxes[1].set_title('ROC Curve')\naxes[1].legend()\nplt.tight_layout()\nplt.show()"),
    md("## 5. Multiclass Classification (One-vs-Rest)\n\nLogistic regression extends to K classes using either:\n- **One-vs-Rest (OvR)**: K binary classifiers, one per class\n- **Softmax (multinomial)**: single model with softmax output"),
    code("iris = load_iris()\nX_i, y_i = iris.data, iris.target\nX_tr, X_te, y_tr, y_te = train_test_split(X_i, y_i, test_size=0.2, random_state=42)\n\nfor solver_name, multi in [('OvR', 'ovr'), ('Softmax', 'multinomial')]:\n    pipe = Pipeline([\n        ('scaler', StandardScaler()),\n        ('clf', LogisticRegression(multi_class=multi, solver='lbfgs', max_iter=200))\n    ])\n    pipe.fit(X_tr, y_tr)\n    acc = accuracy_score(y_te, pipe.predict(X_te))\n    print(f'{solver_name:10s}: accuracy = {acc:.3f}')"),
    code("# Decision boundary visualisation (2 features only)\nfrom matplotlib.colors import ListedColormap\n\nX2 = iris.data[:, :2]  # sepal length and width only\nX_tr2, X_te2, y_tr2, y_te2 = train_test_split(X2, y_i, test_size=0.2, random_state=42)\n\npipe2 = Pipeline([('scaler', StandardScaler()),\n                  ('clf', LogisticRegression(multi_class='ovr', max_iter=200))])\npipe2.fit(X_tr2, y_tr2)\n\nx_min, x_max = X2[:,0].min()-0.5, X2[:,0].max()+0.5\ny_min, y_max = X2[:,1].min()-0.5, X2[:,1].max()+0.5\nxx, yy = np.meshgrid(np.linspace(x_min, x_max, 200),\n                     np.linspace(y_min, y_max, 200))\nZ = pipe2.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)\n\nfig, ax = plt.subplots(figsize=(7, 5))\nax.contourf(xx, yy, Z, alpha=0.3, cmap=ListedColormap(['#FF9999','#99FF99','#9999FF']))\nscatter = ax.scatter(X2[:,0], X2[:,1], c=y_i, cmap=ListedColormap(['#CC0000','#00AA00','#0000CC']),\n                     edgecolors='white', s=40)\nax.set_xlabel(iris.feature_names[0])\nax.set_ylabel(iris.feature_names[1])\nax.set_title('Logistic Regression Decision Boundaries (Iris)')\nplt.colorbar(scatter, ax=ax, ticks=[0,1,2])\nplt.tight_layout()\nplt.show()"),
    md("## Exercises\n\n1. Using the breast cancer dataset, tune the regularization parameter `C` (try `C = [0.001, 0.01, 0.1, 1, 10, 100]`) with 5-fold cross-validation. Plot validation accuracy vs `C`.\n2. Compute **precision, recall, and F1-score** manually from the confusion matrix values (TP, FP, FN, TN). Verify against `classification_report`.\n3. The **ROC AUC** measures a classifier's ability regardless of the decision threshold. Change the threshold from 0.5 to 0.3 for the cancer classifier. How does the confusion matrix change? What trade-off are you making?\n4. Apply logistic regression to the **digits dataset** (`sklearn.datasets.load_digits`) — a 10-class problem. What accuracy do you achieve?\n\n## Reflection Questions\n- What does the coefficient for a feature tell you in logistic regression? (Think in terms of odds ratios.)\n- Precision and Recall are often in tension. In a cancer screening test, which would you prioritise and why?\n- What is the difference between `predict()` and `predict_proba()` — when would you use each?\n\n---\n**Next →** `08_svm.ipynb`"),
])

# ===========================================================================
# 08 — SUPPORT VECTOR MACHINES
# ===========================================================================
save("08_svm.ipynb", [
    md("# Notebook 8: Support Vector Machines (SVM)\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Explain the concept of maximum-margin classification\n- Understand support vectors and the decision hyperplane\n- Describe the kernel trick for non-linear boundaries\n- Apply SVM to classification and compare with other classifiers\n- Tune the `C` and `gamma` hyperparameters"),
    md("## 1. The Core Idea: Maximum Margin\n\nGiven linearly separable data, infinitely many hyperplanes can separate the two classes. Which one is best?\n\n**SVM picks the hyperplane that maximises the margin** — the width of the empty \"street\" between the two classes.\n\n- The data points that lie on the margin boundaries are called **support vectors** — they are the only points that \"matter\" for the decision boundary.\n- A larger margin → better generalisation to unseen data.\n\n$$\\text{Decision hyperplane}: \\mathbf{w}^T \\mathbf{x} + b = 0$$\n$$\\text{Margin width} = \\frac{2}{\\|\\mathbf{w}\\|}$$\n\nMaximising the margin is equivalent to minimising $\\|\\mathbf{w}\\|$ subject to correct classification."),
    code("import numpy as np\nimport matplotlib.pyplot as plt\nfrom sklearn.svm import SVC\nfrom sklearn.datasets import make_classification, make_circles, make_moons, load_iris\nfrom sklearn.model_selection import train_test_split, GridSearchCV\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.metrics import classification_report\nimport warnings; warnings.filterwarnings('ignore')\n\nnp.random.seed(42)"),
    code("# Generate linearly separable data and visualise the maximum-margin hyperplane\nfrom sklearn.datasets import make_blobs\nX_lin, y_lin = make_blobs(n_samples=60, centers=2, cluster_std=0.9, random_state=6)\n\nsvm_lin = SVC(kernel='linear', C=1e10)  # hard margin\nsvm_lin.fit(X_lin, y_lin)\n\ndef plot_svm_decision(model, X, y, ax, title):\n    x_min, x_max = X[:,0].min()-1, X[:,0].max()+1\n    y_min, y_max = X[:,1].min()-1, X[:,1].max()+1\n    xx, yy = np.meshgrid(np.linspace(x_min, x_max, 300),\n                         np.linspace(y_min, y_max, 300))\n    Z = model.decision_function(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)\n    ax.contourf(xx, yy, Z, levels=[-1e9, -1, 0, 1, 1e9],\n                colors=['#FF8888','#FFCCCC','#CCFFCC','#88FF88'], alpha=0.4)\n    ax.contour(xx, yy, Z, levels=[-1, 0, 1], linestyles=['--','-','--'],\n               colors='black', linewidths=[1, 2, 1])\n    ax.scatter(X[:,0], X[:,1], c=y, cmap='bwr', edgecolors='white', s=50)\n    # Highlight support vectors\n    sv = model.support_vectors_\n    ax.scatter(sv[:,0], sv[:,1], s=200, facecolors='none', edgecolors='black',\n               linewidths=2, label=f'Support vectors ({len(sv)})')\n    ax.set_title(title)\n    ax.legend(fontsize=8)\n\nfig, ax = plt.subplots(figsize=(7, 5))\nplot_svm_decision(svm_lin, X_lin, y_lin, ax, 'SVM: Maximum Margin (Linear Kernel)')\nplt.tight_layout()\nplt.show()"),
    md("## 2. Soft Margin SVM — The `C` Parameter\n\nReal data is rarely perfectly linearly separable. **Soft Margin SVM** allows some misclassifications:\n\n$$\\min_{\\mathbf{w}, b} \\frac{1}{2}\\|\\mathbf{w}\\|^2 + C \\sum_i \\xi_i$$\n\n- $\\xi_i \\geq 0$ are **slack variables** allowing constraint violations\n- **Large C**: fewer violations allowed → smaller margin, risk of overfitting\n- **Small C**: more violations allowed → larger margin, risk of underfitting"),
    code("X_noisy, y_noisy = make_blobs(n_samples=100, centers=2, cluster_std=2.0, random_state=6)\n\nfig, axes = plt.subplots(1, 3, figsize=(15, 4))\nfor ax, C_val in zip(axes, [0.01, 1.0, 100]):\n    svm = SVC(kernel='linear', C=C_val)\n    svm.fit(X_noisy, y_noisy)\n    plot_svm_decision(svm, X_noisy, y_noisy, ax, f'C = {C_val}')\nplt.suptitle('Effect of C on Soft Margin SVM')\nplt.tight_layout()\nplt.show()"),
    md("## 3. The Kernel Trick for Non-linear Data\n\nMany real datasets are **not linearly separable** in their original feature space.\n\n**Idea**: Map data to a higher-dimensional space where it becomes linearly separable.\n\nThe **kernel trick** computes inner products in the high-dimensional space *without explicitly computing the transformation* — making it computationally feasible.\n\n| Kernel | Formula | Use case |\n|--------|---------|----------|\n| **Linear** | $\\mathbf{x}^T \\mathbf{x}'$ | Linearly separable; high-dim sparse text |\n| **RBF (Gaussian)** | $\\exp(-\\gamma \\|\\mathbf{x}-\\mathbf{x}'\\|^2)$ | Most common; smooth boundaries |\n| **Polynomial** | $(\\mathbf{x}^T \\mathbf{x}' + r)^d$ | Polynomial features implicitly |"),
    code("X_circles, y_circles = make_circles(n_samples=200, noise=0.1, factor=0.3, random_state=42)\nX_moons,   y_moons   = make_moons(n_samples=200, noise=0.15, random_state=42)\n\nfig, axes = plt.subplots(2, 3, figsize=(15, 8))\ndatasets = [(X_circles, y_circles, 'Circles'), (X_moons, y_moons, 'Moons')]\nkernels  = ['linear', 'rbf', 'poly']\n\nfor row, (X_d, y_d, dname) in enumerate(datasets):\n    for col, kern in enumerate(kernels):\n        ax = axes[row][col]\n        svm_k = SVC(kernel=kern, C=1.0, gamma='scale')\n        svm_k.fit(X_d, y_d)\n        x_min, x_max = X_d[:,0].min()-0.5, X_d[:,0].max()+0.5\n        y_min, y_max = X_d[:,1].min()-0.5, X_d[:,1].max()+0.5\n        xx, yy = np.meshgrid(np.linspace(x_min,x_max,200), np.linspace(y_min,y_max,200))\n        Z = svm_k.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)\n        ax.contourf(xx, yy, Z, alpha=0.3, cmap='bwr')\n        ax.scatter(X_d[:,0], X_d[:,1], c=y_d, cmap='bwr', edgecolors='white', s=25)\n        acc = svm_k.score(X_d, y_d)\n        ax.set_title(f'{dname} + {kern} kernel\\nAcc={acc:.2f}')\n        ax.set_xticks([]); ax.set_yticks([])\nplt.tight_layout()\nplt.show()"),
    md("## 4. SVM on a Real Dataset and Hyperparameter Tuning"),
    code("from sklearn.datasets import load_breast_cancer\ncancer = load_breast_cancer()\nX_c, y_c = cancer.data, cancer.target\n\nX_tr, X_te, y_tr, y_te = train_test_split(X_c, y_c, test_size=0.2, random_state=42)\n\n# Grid search for best C and gamma\npipe = Pipeline([('scaler', StandardScaler()), ('svm', SVC(kernel='rbf', probability=True))])\nparam_grid = {'svm__C': [0.1, 1, 10], 'svm__gamma': ['scale', 0.01, 0.001]}\n\ngrid = GridSearchCV(pipe, param_grid, cv=5, scoring='accuracy', n_jobs=-1)\ngrid.fit(X_tr, y_tr)\n\nprint(f'Best params : {grid.best_params_}')\nprint(f'CV accuracy : {grid.best_score_:.4f}')\n\nbest_model = grid.best_estimator_\nprint(f'Test accuracy: {best_model.score(X_te, y_te):.4f}')"),
    code("# Visualise grid search results\nimport pandas as pd\nresults = pd.DataFrame(grid.cv_results_)\npivot = results.pivot_table(values='mean_test_score',\n                             index='param_svm__gamma',\n                             columns='param_svm__C')\nfig, ax = plt.subplots(figsize=(7, 4))\nim = ax.imshow(pivot.values, cmap='YlOrRd', vmin=pivot.values.min(), vmax=pivot.values.max())\nax.set_xticks(range(len(pivot.columns))); ax.set_xticklabels(pivot.columns)\nax.set_yticks(range(len(pivot.index))); ax.set_yticklabels(pivot.index)\nax.set_xlabel('C'); ax.set_ylabel('gamma')\nax.set_title('Grid Search: Validation Accuracy')\nplt.colorbar(im, ax=ax)\nfor i in range(len(pivot.index)):\n    for j in range(len(pivot.columns)):\n        ax.text(j, i, f'{pivot.values[i,j]:.3f}', ha='center', va='center', fontsize=9)\nplt.tight_layout()\nplt.show()"),
    md("## Exercises\n\n1. Using the Iris dataset, train an SVM with an RBF kernel and visualise the decision boundaries for all three pairs of features.\n2. What happens when you set `C=1e-6` vs `C=1e6` on a noisy dataset? Describe and plot the difference.\n3. The `gamma` parameter controls the RBF kernel width. A very high `gamma` means each sample has a small region of influence — does this lead to overfitting or underfitting? Verify experimentally.\n4. Compare SVM (RBF) with Logistic Regression on the breast cancer dataset in terms of accuracy, training time, and interpretability.\n\n## Reflection Questions\n- Why is feature scaling critical for SVM but less important for tree-based models?\n- Support vectors define the decision boundary. If you remove non-support-vector training points, does the boundary change? Why?\n- Why can't you easily interpret SVM coefficients the way you can with logistic regression?\n\n---\n**Next →** `09_knn_naive_bayes.ipynb`"),
])

# ===========================================================================
# 09 — KNN AND NAIVE BAYES
# ===========================================================================
save("09_knn_naive_bayes.ipynb", [
    md("# Notebook 9: K-Nearest Neighbours and Naive Bayes\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Explain the KNN algorithm and choose K\n- Understand the curse of dimensionality\n- Derive Bayes' theorem and understand conditional independence\n- Apply Gaussian, Multinomial, and Bernoulli Naive Bayes\n- Know when each algorithm is appropriate"),
    md("## Part A: K-Nearest Neighbours (KNN)\n\n## 1. The Algorithm\n\nKNN is beautifully simple:\n1. Compute the distance from the query point to every training point\n2. Find the K closest points\n3. **Classification**: take a majority vote\n4. **Regression**: take the average\n\nKNN makes **no assumptions about the data distribution** — it is a **non-parametric** method. The model *is* the training data."),
    code("import numpy as np\nimport matplotlib.pyplot as plt\nfrom sklearn.neighbors import KNeighborsClassifier\nfrom sklearn.datasets import load_iris, make_moons, load_breast_cancer\nfrom sklearn.model_selection import train_test_split, cross_val_score\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.pipeline import Pipeline\nfrom matplotlib.colors import ListedColormap\nimport warnings; warnings.filterwarnings('ignore')\n\nnp.random.seed(42)\n\n# Simple KNN illustration\nfrom sklearn.datasets import make_blobs\nX_blob, y_blob = make_blobs(n_samples=100, centers=3, cluster_std=1.2, random_state=5)\n\nknn3 = KNeighborsClassifier(n_neighbors=3).fit(X_blob, y_blob)\n\nx_min, x_max = X_blob[:,0].min()-1, X_blob[:,0].max()+1\ny_min, y_max = X_blob[:,1].min()-1, X_blob[:,1].max()+1\nxx, yy = np.meshgrid(np.linspace(x_min,x_max,300), np.linspace(y_min,y_max,300))\nZ = knn3.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)\n\nfig, ax = plt.subplots(figsize=(7, 5))\ncmap_light = ListedColormap(['#FFAAAA','#AAFFAA','#AAAAFF'])\ncmap_bold  = ListedColormap(['#FF0000','#00AA00','#0000FF'])\nax.contourf(xx, yy, Z, cmap=cmap_light, alpha=0.6)\nax.scatter(X_blob[:,0], X_blob[:,1], c=y_blob, cmap=cmap_bold, edgecolors='white', s=50)\n\n# Show query point and its 3 nearest neighbours\nquery = np.array([[1.0, 3.0]])\ndists = np.sqrt(((X_blob - query)**2).sum(axis=1))\nnearest_idx = np.argsort(dists)[:3]\nfor idx in nearest_idx:\n    ax.plot([query[0,0], X_blob[idx,0]], [query[0,1], X_blob[idx,1]],\n            'k--', alpha=0.5)\nax.scatter(*query[0], s=300, c='yellow', edgecolors='black', zorder=5, marker='*', label='Query')\nax.scatter(X_blob[nearest_idx,0], X_blob[nearest_idx,1],\n           s=200, facecolors='none', edgecolors='black', linewidths=2, label='3 Nearest Neighbours')\nax.set_title('KNN: 3 Nearest Neighbours')\nax.legend()\nplt.tight_layout()\nplt.show()"),
    md("## 2. Choosing K — The Bias-Variance Trade-off\n\n- **Small K** (e.g., K=1): very flexible, fits noise, high variance (overfitting)\n- **Large K** (e.g., K=n): very smooth, underfitting, high bias\n\nWe use cross-validation to find the best K."),
    code("X_m, y_m = make_moons(n_samples=400, noise=0.2, random_state=42)\nX_tr, X_te, y_tr, y_te = train_test_split(X_m, y_m, test_size=0.2, random_state=42)\n\nK_values = range(1, 31)\ntrain_acc, test_acc = [], []\nfor k in K_values:\n    pipe = Pipeline([('scaler', StandardScaler()),\n                     ('knn', KNeighborsClassifier(n_neighbors=k))])\n    pipe.fit(X_tr, y_tr)\n    train_acc.append(pipe.score(X_tr, y_tr))\n    test_acc.append(pipe.score(X_te, y_te))\n\nbest_k = K_values[np.argmax(test_acc)]\nprint(f'Best K = {best_k}, Test Accuracy = {max(test_acc):.3f}')\n\nfig, ax = plt.subplots(figsize=(9, 4))\nax.plot(K_values, train_acc, label='Train accuracy', marker='o')\nax.plot(K_values, test_acc,  label='Test accuracy',  marker='s')\nax.axvline(best_k, color='red', linestyle='--', label=f'Best K={best_k}')\nax.set_xlabel('K')\nax.set_ylabel('Accuracy')\nax.set_title('KNN: Accuracy vs K')\nax.legend()\nplt.tight_layout()\nplt.show()"),
    md("## 3. The Curse of Dimensionality\n\nKNN relies on **distance**. In high dimensions, all points become roughly equidistant — the notion of \"nearest\" breaks down.\n\n> In 10 dimensions, you need exponentially more data to densely cover the space."),
    code("# Demonstrate how fraction of volume in a hypersphere shrinks\ndims = range(1, 30)\n# Volume of unit hypersphere as a fraction of unit hypercube\nimport math\ndef vol_fraction(d, r=0.1):\n    # Vol of hypersphere / Vol of hypercube [0,1]^d\n    return (math.pi**(d/2) * r**d) / math.gamma(d/2 + 1)\n\nfracs = [vol_fraction(d) for d in dims]\nfig, ax = plt.subplots(figsize=(9, 4))\nax.semilogy(list(dims), fracs, marker='o')\nax.set_xlabel('Number of dimensions')\nax.set_ylabel('Volume fraction (log scale)')\nax.set_title('Curse of Dimensionality: Hypersphere Volume Fraction')\nax.set_title('Volume of unit hypersphere relative to hypercube shrinks exponentially')\nplt.tight_layout()\nplt.show()\nprint('At 20 dimensions, a hypersphere covers essentially 0% of the hypercube volume!')"),
    md("## Part B: Naive Bayes\n\n## 4. Bayes' Theorem\n\n$$P(y | \\mathbf{x}) = \\frac{P(\\mathbf{x} | y) \\cdot P(y)}{P(\\mathbf{x})}$$\n\n- $P(y)$ — **prior**: how common is this class?\n- $P(\\mathbf{x} | y)$ — **likelihood**: how likely are these features given the class?\n- $P(y | \\mathbf{x})$ — **posterior**: what we want to predict\n\n### The \"Naive\" Assumption\nFeatures are **conditionally independent** given the class:\n\n$$P(\\mathbf{x} | y) = \\prod_{j=1}^p P(x_j | y)$$\n\nThis is rarely true in practice, but Naive Bayes works surprisingly well despite it."),
    code("# Manual Naive Bayes illustration with toy data\n# Weather example: will someone play tennis?\nprint('Bayes Theorem Example: Will someone play tennis?\\n')\n\n# P(Sunny) = 5/14, P(Sunny|Play) = 2/9, P(Play) = 9/14\nP_play  = 9/14\nP_sunny = 5/14\nP_sunny_given_play = 2/9\n\nP_play_given_sunny = (P_sunny_given_play * P_play) / P_sunny\nprint(f'P(Play)             = {P_play:.3f}')\nprint(f'P(Sunny)            = {P_sunny:.3f}')\nprint(f'P(Sunny|Play)       = {P_sunny_given_play:.3f}')\nprint(f'P(Play|Sunny)       = {P_play_given_sunny:.3f}')\nprint(f'Decision: {\"PLAY\" if P_play_given_sunny > 0.5 else \"NO PLAY\"} (threshold 0.5)')"),
    code("from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB\nfrom sklearn.datasets import load_breast_cancer\nfrom sklearn.metrics import classification_report\n\n# Gaussian NB for continuous features\ncancer = load_breast_cancer()\nX_c, y_c = cancer.data, cancer.target\nX_tr, X_te, y_tr, y_te = train_test_split(X_c, y_c, test_size=0.2, random_state=42)\n\ngnb = GaussianNB()\ngnb.fit(X_tr, y_tr)\ny_pred_gnb = gnb.predict(X_te)\nprint('Gaussian Naive Bayes on Breast Cancer:')\nprint(classification_report(y_te, y_pred_gnb, target_names=cancer.target_names))"),
    code("# Compare KNN vs Naive Bayes on the Iris dataset\nfrom sklearn.datasets import load_iris\niris = load_iris()\nX_i, y_i = iris.data, iris.target\nX_tr_i, X_te_i, y_tr_i, y_te_i = train_test_split(X_i, y_i, test_size=0.2, random_state=42)\n\nmodels = [\n    ('KNN (k=5)',       Pipeline([('scaler', StandardScaler()), ('clf', KNeighborsClassifier(5))])),\n    ('KNN (k=15)',      Pipeline([('scaler', StandardScaler()), ('clf', KNeighborsClassifier(15))])),\n    ('Gaussian NB',    GaussianNB()),\n]\n\nprint(f'{'Model':<20} Train Acc   Test Acc   CV Acc (5-fold)')\nprint('-' * 60)\nfor name, model in models:\n    model.fit(X_tr_i, y_tr_i)\n    tr_acc = model.score(X_tr_i, y_tr_i)\n    te_acc = model.score(X_te_i, y_te_i)\n    cv_acc = cross_val_score(model, X_i, y_i, cv=5).mean()\n    print(f'{name:<20} {tr_acc:.3f}       {te_acc:.3f}      {cv_acc:.3f}')"),
    md("## 5. When to Use Each Algorithm\n\n| | KNN | Naive Bayes |\n|--|-----|--------------|\n| **Speed (train)** | O(1) | O(n·p) |\n| **Speed (predict)** | O(n·p) | O(K·p) |\n| **Works well with** | Small, low-dim data | Text, large datasets |\n| **Handles missing** | ❌ | ✅ (skip feature) |\n| **Interpretable** | Limited | ✅ (priors/likelihoods) |\n| **Key weakness** | Slow prediction, curse of dim | Strong independence assumption |"),
    md("## Exercises\n\n1. Implement **weighted KNN** where closer neighbours get more vote weight: `weight='distance'` in sklearn. Compare with uniform weights.\n2. Use `KNeighborsRegressor` to predict California housing prices. What is the RMSE? Compare with linear regression.\n3. The **class prior** in Naive Bayes can be manually adjusted. Experiment with `var_smoothing` in `GaussianNB` and observe its effect.\n4. Build a **spam filter** using `MultinomialNB` on a small bag-of-words dataset (you'll revisit this in Notebook 12).\n\n## Reflection Questions\n- KNN has no explicit training step — is that an advantage or a disadvantage in production?\n- Why does Naive Bayes often work well on text classification despite the obviously violated independence assumption?\n- What is Laplace smoothing in Naive Bayes and why is it necessary?\n\n---\n**Next →** `10_decision_trees.ipynb`"),
])
