#!/usr/bin/env python3
"""DCS 404 — Part 2: Notebooks 10-18"""
import json, os, uuid

OUT = "notebooks"
os.makedirs(OUT, exist_ok=True)

def nb(cells):
    return {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py", "mimetype": "text/x-python",
                "name": "python", "pygments_lexer": "ipython3", "version": "3.9.0"
            }
        },
        "cells": cells
    }

def md(s):
    return {"cell_type": "markdown", "id": uuid.uuid4().hex[:8], "metadata": {}, "source": s}

def code(s):
    return {"cell_type": "code", "id": uuid.uuid4().hex[:8], "metadata": {},
            "execution_count": None, "outputs": [], "source": s}

def save(name, cells):
    path = os.path.join(OUT, name)
    with open(path, "w") as f:
        json.dump(nb(cells), f, indent=1)
    print(f"  Created: {path}")

# ===========================================================================
# 10 — DECISION TREES
# ===========================================================================
save("10_decision_trees.ipynb", [
    md("# Notebook 10: Decision Trees\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Understand how a decision tree splits data\n- Compute information gain and Gini impurity\n- Grow, visualise, and prune a decision tree\n- Control tree depth to prevent overfitting\n- Extract feature importances"),
    md("## 1. What Is a Decision Tree?\n\nA decision tree partitions the feature space into axis-aligned regions, each assigned a prediction. Each **internal node** tests one feature; each **leaf** gives a prediction.\n\n```\n             Is petal_length < 2.45?\n            /                        \\\n          YES                         NO\n       Setosa                 Is petal_width < 1.75?\n                              /                    \\\n                           YES                      NO\n                        Versicolor              Virginica\n```\n\n**Why trees?**\n- Human-readable rules — fully interpretable\n- Handle mixed feature types natively\n- No feature scaling required\n- Naturally capture non-linear interactions"),
    md("## 2. Splitting Criteria\n\n### Gini Impurity\n$$G = 1 - \\sum_{k=1}^K p_k^2$$\n\n$G = 0$ means a pure node (only one class). $G = 0.5$ is maximum impurity for a binary problem.\n\n### Information Gain (Entropy)\n$$H = -\\sum_{k=1}^K p_k \\log_2 p_k$$\n$$\\text{IG} = H(\\text{parent}) - \\frac{n_L}{n} H(\\text{left}) - \\frac{n_R}{n} H(\\text{right})$$\n\nAt each node, the tree exhaustively searches **all features and all thresholds** to find the split with the highest Information Gain (or lowest Gini after split)."),
    code("import numpy as np\nimport matplotlib.pyplot as plt\nfrom sklearn.tree import DecisionTreeClassifier, plot_tree, export_text\nfrom sklearn.datasets import load_iris, load_breast_cancer\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import accuracy_score\nimport warnings; warnings.filterwarnings('ignore')\n\nnp.random.seed(42)\n\n# Visualise Gini and Entropy\np = np.linspace(0.001, 0.999, 300)\ngini    = 1 - p**2 - (1-p)**2\nentropy = -(p*np.log2(p) + (1-p)*np.log2(1-p))\n\nfig, ax = plt.subplots(figsize=(8, 4))\nax.plot(p, gini,          label='Gini impurity',     linewidth=2)\nax.plot(p, entropy * 0.5, label='Entropy (×0.5)',    linewidth=2, linestyle='--')\nax.set_xlabel('p (fraction of positive class)')\nax.set_ylabel('Impurity')\nax.set_title('Gini vs Entropy Impurity Measures')\nax.legend()\nplt.tight_layout()\nplt.show()"),
    code("# Manual information-gain calculation\ndef entropy(y):\n    _, counts = np.unique(y, return_counts=True)\n    p = counts / counts.sum()\n    return -np.sum(p * np.log2(p + 1e-12))\n\ndef info_gain(y, y_left, y_right):\n    n, n_l, n_r = len(y), len(y_left), len(y_right)\n    return entropy(y) - (n_l/n)*entropy(y_left) - (n_r/n)*entropy(y_right)\n\niris = load_iris()\nX, y = iris.data, iris.target\npetal_length = X[:, 2]\n\nbest_t, best_ig = max(\n    ((t, info_gain(y, y[petal_length<=t], y[petal_length>t]))\n     for t in np.unique(petal_length)\n     if len(y[petal_length<=t])>0 and len(y[petal_length>t])>0),\n    key=lambda x: x[1]\n)\nprint(f'Best threshold for petal_length: {best_t:.1f} cm')\nprint(f'Information Gain               : {best_ig:.4f}')"),
    md("## 3. Growing a Tree with scikit-learn"),
    code("X_tr, X_te, y_tr, y_te = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)\n\ntree = DecisionTreeClassifier(max_depth=3, random_state=42)\ntree.fit(X_tr, y_tr)\n\nprint(f'Train accuracy: {tree.score(X_tr, y_tr):.3f}')\nprint(f'Test  accuracy: {tree.score(X_te, y_te):.3f}')\n\nfig, ax = plt.subplots(figsize=(16, 6))\nplot_tree(tree, feature_names=iris.feature_names,\n          class_names=iris.target_names,\n          filled=True, ax=ax, fontsize=8)\nax.set_title('Decision Tree (max_depth=3) — Iris')\nplt.tight_layout()\nplt.show()\n\nprint('\\nText representation:')\nprint(export_text(tree, feature_names=list(iris.feature_names)))"),
    md("## 4. Bias-Variance via Depth"),
    code("depths = range(1, 15)\ntrain_accs, test_accs = [], []\nfor d in depths:\n    t = DecisionTreeClassifier(max_depth=d, random_state=42)\n    t.fit(X_tr, y_tr)\n    train_accs.append(t.score(X_tr, y_tr))\n    test_accs.append(t.score(X_te, y_te))\n\nbest_d = list(depths)[np.argmax(test_accs)]\nfig, ax = plt.subplots(figsize=(9, 4))\nax.plot(depths, train_accs, marker='o', label='Train')\nax.plot(depths, test_accs,  marker='s', label='Test')\nax.axvline(best_d, color='red', linestyle='--', label=f'Best depth={best_d}')\nax.set_xlabel('max_depth'); ax.set_ylabel('Accuracy')\nax.set_title('Decision Tree: Accuracy vs Depth (Iris)')\nax.legend()\nplt.tight_layout()\nplt.show()\nprint(f'Unconstrained tree: train={train_accs[-1]:.3f}, test={test_accs[-1]:.3f} — overfitting!')\nprint(f'Best depth={best_d}: test accuracy={max(test_accs):.3f}')"),
    md("## 5. Feature Importances"),
    code("cancer = load_breast_cancer()\nX_c, y_c = cancer.data, cancer.target\nX_tr_c, X_te_c, y_tr_c, y_te_c = train_test_split(X_c, y_c, test_size=0.2, random_state=42)\n\ntree_c = DecisionTreeClassifier(max_depth=5, random_state=42)\ntree_c.fit(X_tr_c, y_tr_c)\nprint(f'Breast Cancer — Test accuracy: {tree_c.score(X_te_c, y_te_c):.3f}')\n\nimps = tree_c.feature_importances_\nidx = np.argsort(imps)[::-1][:10]\nfig, ax = plt.subplots(figsize=(10, 4))\nax.bar(range(10), imps[idx], color='steelblue')\nax.set_xticks(range(10))\nax.set_xticklabels([cancer.feature_names[i] for i in idx], rotation=45, ha='right', fontsize=9)\nax.set_ylabel('Importance')\nax.set_title('Top 10 Feature Importances')\nplt.tight_layout()\nplt.show()"),
    md("## 6. Decision Boundary Visualisation"),
    code("from matplotlib.colors import ListedColormap\n\nX2 = iris.data[:, 2:4]  # petal length & width\ndt2 = DecisionTreeClassifier(max_depth=3, random_state=42).fit(X2, iris.target)\n\nx_min, x_max = X2[:,0].min()-0.3, X2[:,0].max()+0.3\ny_min, y_max = X2[:,1].min()-0.3, X2[:,1].max()+0.3\nxx, yy = np.meshgrid(np.linspace(x_min,x_max,300), np.linspace(y_min,y_max,300))\nZ = dt2.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)\n\nfig, ax = plt.subplots(figsize=(8, 5))\nax.contourf(xx, yy, Z, alpha=0.3, cmap=ListedColormap(['#FF9999','#99FF99','#9999FF']))\nax.scatter(X2[:,0], X2[:,1], c=iris.target,\n           cmap=ListedColormap(['#CC0000','#00AA00','#0000CC']),\n           edgecolors='white', s=40)\nax.set_xlabel('Petal Length (cm)'); ax.set_ylabel('Petal Width (cm)')\nax.set_title('Decision Tree Regions (Iris — petal features)')\nplt.tight_layout()\nplt.show()"),
    md("## Exercises\n\n1. Train with `max_depth=None`. What is the training accuracy? What does this tell you about overfitting?\n2. Use `cost_complexity_pruning_path` to find the optimal `ccp_alpha` via cross-validation.\n3. Implement Gini impurity manually and verify it matches `tree.tree_.impurity` for the root node.\n4. Apply a decision tree to the Titanic dataset and extract the rules as text — what does the tree say is most predictive of survival?\n\n## Reflection Questions\n- Decision trees create axis-aligned splits. What kinds of true decision boundaries are hard to represent?\n- Why do trees overfit when unconstrained, and what are three hyperparameters that control complexity?\n- Feature importances from a single tree can be noisy. How do Random Forests address this?\n\n---\n**Next →** `11_ensemble_methods.ipynb`"),
])

# ===========================================================================
# 11 — ENSEMBLE METHODS
# ===========================================================================
save("11_ensemble_methods.ipynb", [
    md("# Notebook 11: Ensemble Methods — Random Forest and Boosting\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Understand bagging and boosting as complementary strategies\n- Explain why Random Forest reduces variance\n- Implement AdaBoost and Gradient Boosting\n- Compare ensemble methods on real data\n- Use feature importances from Random Forest"),
    md("## 1. Why Ensembles?\n\nIf you have 25 independent classifiers each with 70% accuracy and take a majority vote:\n\n$$P(\\text{majority correct}) = \\sum_{k=13}^{25} \\binom{25}{k} 0.7^k 0.3^{25-k} \\approx 0.997$$\n\nThe key ingredient is **diversity** — the classifiers must make different mistakes.\n\n### Two Strategies\n| | **Bagging** | **Boosting** |\n|--|------------|-------------|\n| Training | Parallel | Sequential |\n| Focus | All samples equally | Misclassified samples more |\n| Reduces | Variance | Bias |\n| Example | Random Forest | AdaBoost, GradientBoosting |"),
    code("import numpy as np\nimport matplotlib.pyplot as plt\nfrom sklearn.ensemble import (\n    RandomForestClassifier, AdaBoostClassifier,\n    GradientBoostingClassifier, BaggingClassifier\n)\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.datasets import load_breast_cancer\nfrom sklearn.model_selection import train_test_split, cross_val_score\nimport warnings; warnings.filterwarnings('ignore')\n\nnp.random.seed(42)\ncancer = load_breast_cancer()\nX, y = cancer.data, cancer.target\nX_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42)"),
    md("## 2. Random Forest = Bagging + Random Feature Selection\n\n**Bagging**: sample B bootstrap datasets → train one tree on each → vote.\n\n**Random Forest** adds: at each split, only consider $\\sqrt{p}$ randomly chosen features. This **decorrelates** the trees — they make more independent errors, so the majority vote is stronger."),
    code("models = [\n    ('Single Tree',   DecisionTreeClassifier(max_depth=5, random_state=42)),\n    ('Bagging (50)',  BaggingClassifier(DecisionTreeClassifier(max_depth=5),\n                                        n_estimators=50, random_state=42)),\n    ('Random Forest', RandomForestClassifier(n_estimators=100, random_state=42)),\n]\n\nprint(f'{\"Model\":<25} Train    Test    CV-5')\nprint('-' * 52)\nfor name, m in models:\n    m.fit(X_tr, y_tr)\n    tr = m.score(X_tr, y_tr)\n    te = m.score(X_te, y_te)\n    cv = cross_val_score(m, X, y, cv=5).mean()\n    print(f'{name:<25} {tr:.4f}   {te:.4f}   {cv:.4f}')"),
    code("# Effect of number of trees\nn_range = [1, 5, 10, 25, 50, 100, 200]\naccs = []\nfor n in n_range:\n    rf = RandomForestClassifier(n_estimators=n, random_state=42)\n    rf.fit(X_tr, y_tr)\n    accs.append(rf.score(X_te, y_te))\n\nfig, ax = plt.subplots(figsize=(9, 4))\nax.semilogx(n_range, accs, marker='o', linewidth=2)\nax.set_xlabel('Number of trees (log scale)')\nax.set_ylabel('Test Accuracy')\nax.set_title('Random Forest: Accuracy vs Number of Trees')\nplt.tight_layout(); plt.show()"),
    code("# Feature importances with uncertainty\nrf = RandomForestClassifier(n_estimators=200, random_state=42).fit(X_tr, y_tr)\nimps = rf.feature_importances_\nstd  = np.std([t.feature_importances_ for t in rf.estimators_], axis=0)\nidx  = np.argsort(imps)[::-1][:12]\n\nfig, ax = plt.subplots(figsize=(11, 4))\nax.bar(range(12), imps[idx], yerr=std[idx], capsize=3, color='steelblue')\nax.set_xticks(range(12))\nax.set_xticklabels([cancer.feature_names[i] for i in idx], rotation=45, ha='right', fontsize=8)\nax.set_ylabel('Importance ± std')\nax.set_title('Random Forest Feature Importances')\nplt.tight_layout(); plt.show()"),
    md("## 3. AdaBoost\n\n**Algorithm**:\n1. All samples start with equal weight\n2. Train a weak classifier (often a depth-1 stump)\n3. Increase weights of misclassified points\n4. Repeat T rounds\n5. Final prediction: weighted vote of all classifiers\n\nThe weight of classifier $m$ in the final vote is $\\alpha_m = \\frac{1}{2}\\ln\\frac{1-\\epsilon_m}{\\epsilon_m}$ where $\\epsilon_m$ is its weighted error rate."),
    code("ada = AdaBoostClassifier(\n    estimator=DecisionTreeClassifier(max_depth=1),\n    n_estimators=200, learning_rate=1.0, random_state=42\n)\nada.fit(X_tr, y_tr)\n\nstaged_tr = list(ada.staged_score(X_tr, y_tr))\nstaged_te = list(ada.staged_score(X_te, y_te))\n\nfig, ax = plt.subplots(figsize=(9, 4))\nax.plot(staged_tr, label='Train')\nax.plot(staged_te, label='Test')\nax.set_xlabel('Boosting rounds')\nax.set_ylabel('Accuracy')\nax.set_title('AdaBoost: Staged Accuracy')\nax.legend()\nplt.tight_layout(); plt.show()\nprint(f'AdaBoost final test accuracy: {ada.score(X_te, y_te):.4f}')"),
    md("## 4. Gradient Boosting\n\nEach new tree is fitted to the **negative gradient of the loss** — i.e., the residual errors of the current ensemble:\n\n$$F_m(x) = F_{m-1}(x) + \\eta \\cdot h_m(x)$$\n\n**Key hyperparameters**:\n- `n_estimators`: number of trees\n- `learning_rate` $\\eta$: shrinkage (lower = need more trees)\n- `max_depth`: typically 3–5\n- `subsample`: fraction of samples per tree (< 1.0 adds randomness = Stochastic GB)"),
    code("gb = GradientBoostingClassifier(\n    n_estimators=200, learning_rate=0.05,\n    max_depth=3, subsample=0.8, random_state=42\n)\ngb.fit(X_tr, y_tr)\nstaged_te_gb = list(gb.staged_score(X_te, y_te))\nstaged_tr_gb = list(gb.staged_score(X_tr, y_tr))\n\nfig, ax = plt.subplots(figsize=(9, 4))\nax.plot(staged_tr_gb, label='Train')\nax.plot(staged_te_gb, label='Test')\nax.set_xlabel('Boosting rounds')\nax.set_ylabel('Accuracy')\nax.set_title('Gradient Boosting: Staged Accuracy')\nax.legend()\nplt.tight_layout(); plt.show()\nprint(f'Gradient Boosting test accuracy: {gb.score(X_te, y_te):.4f}')"),
    md("## 5. Head-to-Head Comparison"),
    code("all_models = [\n    ('Decision Tree',       DecisionTreeClassifier(max_depth=5, random_state=42)),\n    ('Random Forest',       RandomForestClassifier(n_estimators=100, random_state=42)),\n    ('AdaBoost',            AdaBoostClassifier(n_estimators=100, random_state=42)),\n    ('Gradient Boosting',   GradientBoostingClassifier(n_estimators=100, random_state=42)),\n    ('Logistic Regression', Pipeline([('sc', StandardScaler()),\n                                       ('lr', LogisticRegression(max_iter=1000))])),\n]\n\nresults = {}\nfor name, model in all_models:\n    cv = cross_val_score(model, X, y, cv=10)\n    results[name] = cv\n    print(f'{name:<25} CV: {cv.mean():.4f} ± {cv.std():.4f}')\n\nfig, ax = plt.subplots(figsize=(10, 5))\nax.boxplot(list(results.values()), labels=list(results.keys()), patch_artist=True)\nax.set_ylabel('10-fold CV Accuracy')\nax.set_title('Model Comparison — Breast Cancer')\nax.set_xticklabels(list(results.keys()), rotation=30, ha='right')\nplt.tight_layout(); plt.show()"),
    md("## Exercises\n\n1. Tune `RandomForestClassifier` with `GridSearchCV` over `n_estimators`, `max_depth`, and `max_features`. What combination wins?\n2. Enable `oob_score=True` on Random Forest — it estimates generalisation error from out-of-bag samples without needing a validation set. Compare to 5-fold CV.\n3. Try `subsample=[0.5, 0.7, 1.0]` in Gradient Boosting. Does subsampling help regularise the model?\n4. Look up `HistGradientBoostingClassifier` in sklearn — the fast version. Compare training time on a large dataset.\n\n## Reflection Questions\n- Bagging reduces variance but not bias. Boosting reduces bias. How do these connect to the bias-variance trade-off?\n- Why does Random Forest randomly select features at each split — what would happen without this?\n- If both Random Forest and Gradient Boosting achieve similar accuracy, which would you prefer to deploy and why?\n\n---\n**Next →** `12_text_classification.ipynb`"),
])

# ===========================================================================
# 12 — TEXT CLASSIFICATION
# ===========================================================================
save("12_text_classification.ipynb", [
    md("# Notebook 12: Text Classification — Movie Review Sentiment\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Represent text as numerical features (Bag-of-Words, TF-IDF)\n- Build a text classification pipeline with scikit-learn\n- Apply Naive Bayes, Logistic Regression, and LinearSVC to text\n- Understand what makes text features challenging\n- Interpret which words are most predictive"),
    md("## 1. The Challenge of Text\n\nML models require fixed-length numerical vectors. Raw text is:\n- **Variable length**: reviews range from 1 word to 5000+ words\n- **High-dimensional**: English has 170,000+ words in common use\n- **Sparse**: any single document uses only hundreds of words\n- **Context-dependent**: \"not bad\" is positive; \"good grief\" is negative\n\n### The Classic NLP Pipeline\n```\nRaw text\n  → Tokenise (split into words)\n  → Lowercase, remove punctuation\n  → [Optional] Remove stop words\n  → Vectorise: Bag-of-Words or TF-IDF\nNumerical feature matrix  →  ML classifier\n```"),
    code("import numpy as np\nimport matplotlib.pyplot as plt\nfrom sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer\nfrom sklearn.naive_bayes import MultinomialNB\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.svm import LinearSVC\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.model_selection import cross_val_score\nfrom sklearn.metrics import classification_report, confusion_matrix\nfrom sklearn.datasets import fetch_20newsgroups\nimport warnings; warnings.filterwarnings('ignore')\n\nnp.random.seed(42)"),
    md("## 2. Bag-of-Words (BoW)\n\nCount how many times each word appears in a document:\n\n```\nDoc A: \"I loved this movie! Great acting.\"\nDoc B: \"Terrible film. Worst movie I have seen.\"\n\nVocab: [acting, great, have, i, loved, movie, seen, terrible, this, worst]\nDoc A: [  1,     1,    0,  1,    1,     1,     0,      0,       1,     0]\nDoc B: [  0,     0,    1,  1,    0,     1,     1,      1,       0,     1]\n```\n\n**Problem**: common words (\"the\", \"is\", \"movie\") dominate and carry little meaning."),
    code("corpus = [\n    \"I loved this movie! Fantastic acting.\",\n    \"Terrible film. Worst movie I have seen.\",\n    \"Great story and wonderful cinematography.\",\n    \"Boring and predictable. Waste of time.\",\n    \"Absolutely brilliant. A masterpiece!\",\n    \"Not good at all. Very disappointing.\",\n]\nlabels = ['pos','neg','pos','neg','pos','neg']\n\nvec = CountVectorizer(stop_words='english', lowercase=True)\nX_bow = vec.fit_transform(corpus)\nprint('Vocabulary:', list(vec.vocabulary_.keys()))\nprint(f'Feature matrix shape: {X_bow.shape}  (6 docs × {X_bow.shape[1]} words)')\nprint('\\nDoc 0 non-zero features:')\nfor idx in X_bow[0].nonzero()[1]:\n    print(f'  {vec.get_feature_names_out()[idx]}: {X_bow[0,idx]}')"),
    md("## 3. TF-IDF: Down-weight Common Words\n\n$$\\text{TF-IDF}(t,d) = \\text{TF}(t,d) \\times \\log\\frac{N+1}{\\text{df}(t)+1}$$\n\n- Words appearing in every document get low weight (low IDF)\n- Rare but meaningful words get high weight (high IDF)\n- Much better signal-to-noise ratio than raw counts"),
    code("tfidf = TfidfVectorizer(stop_words='english', lowercase=True)\nX_tfidf = tfidf.fit_transform(corpus)\n\nprint('TF-IDF for Doc 0:')\nfeat_names = tfidf.get_feature_names_out()\nfor idx in X_tfidf[0].nonzero()[1]:\n    print(f'  {feat_names[idx]:20s}: {X_tfidf[0,idx]:.4f}')"),
    md("## 4. Classification on the 20 Newsgroups Dataset\n\nThe 20 Newsgroups dataset contains ~18,000 news articles across 20 topics. We'll use 4 categories for speed."),
    code("categories = ['sci.space','rec.sport.baseball','talk.politics.guns','comp.graphics']\n\ntrain_ng = fetch_20newsgroups(subset='train', categories=categories,\n                               remove=('headers','footers','quotes'))\ntest_ng  = fetch_20newsgroups(subset='test',  categories=categories,\n                               remove=('headers','footers','quotes'))\n\nprint(f'Train: {len(train_ng.data)}, Test: {len(test_ng.data)}')\nprint(f'Categories: {train_ng.target_names}')\nprint(f'\\nSample (truncated):\\n{train_ng.data[0][:250]}...')"),
    code("X_tr, y_tr = train_ng.data, train_ng.target\nX_te, y_te = test_ng.data,  test_ng.target\n\npipelines = [\n    ('NB + BoW',      Pipeline([('v', CountVectorizer(stop_words='english')), ('c', MultinomialNB())])),\n    ('NB + TF-IDF',   Pipeline([('v', TfidfVectorizer(stop_words='english')), ('c', MultinomialNB())])),\n    ('LR + TF-IDF',   Pipeline([('v', TfidfVectorizer(stop_words='english')), ('c', LogisticRegression(max_iter=500))])),\n    ('SVC + TF-IDF',  Pipeline([('v', TfidfVectorizer(stop_words='english')), ('c', LinearSVC())])),\n]\n\nprint(f'{\"Pipeline\":<20} Test Acc')\nprint('-' * 35)\nfor name, pipe in pipelines:\n    pipe.fit(X_tr, y_tr)\n    print(f'{name:<20} {pipe.score(X_te, y_te):.4f}')"),
    code("# Confusion matrix for LinearSVC\nbest_pipe = pipelines[-1][1]\ny_pred = best_pipe.predict(X_te)\ncm = confusion_matrix(y_te, y_pred)\n\nfig, ax = plt.subplots(figsize=(7, 5))\nim = ax.imshow(cm, cmap='Blues')\nplt.colorbar(im, ax=ax)\nshort = [c.split('.')[1] for c in categories]\nax.set_xticks(range(4)); ax.set_xticklabels(short, rotation=30, ha='right')\nax.set_yticks(range(4)); ax.set_yticklabels(short)\nax.set_xlabel('Predicted'); ax.set_ylabel('Actual')\nax.set_title('LinearSVC — 20 Newsgroups Confusion Matrix')\nfor i in range(4):\n    for j in range(4):\n        ax.text(j, i, str(cm[i,j]), ha='center', va='center',\n                color='white' if cm[i,j]>cm.max()/2 else 'black')\nplt.tight_layout(); plt.show()"),
    md("## 5. Interpreting the Model — Which Words Matter?"),
    code("lr_pipe = pipelines[2][1]  # LR + TF-IDF\nvect = lr_pipe.named_steps['v']\nclf  = lr_pipe.named_steps['c']\nfeat = vect.get_feature_names_out()\n\nfig, axes = plt.subplots(1, 4, figsize=(16, 4))\nfor i, (ax, cat) in enumerate(zip(axes, categories)):\n    top_idx = np.argsort(clf.coef_[i])[-10:]\n    ax.barh([feat[j] for j in top_idx], clf.coef_[i][top_idx], color='steelblue')\n    ax.set_title(cat.split('.')[1], fontsize=9)\n    ax.tick_params(labelsize=8)\nplt.suptitle('Top 10 Predictive Words per Category')\nplt.tight_layout(); plt.show()"),
    md("## Exercises\n\n1. Add bigrams (`ngram_range=(1,2)`) to the TF-IDF vectorizer. Does accuracy improve?\n2. Experiment with `max_features=5000` vs unlimited. What is the accuracy-speed trade-off?\n3. Apply the pipeline to a binary sentiment dataset (e.g., IMDB movie reviews CSV). Can you get above 90% accuracy?\n4. What are the most common confusions between `sci.space` and `comp.graphics`? Examine the misclassified documents.\n\n## Reflection Questions\n- TF-IDF treats each word independently. What language patterns does it completely miss?\n- Why did we use `remove=('headers','footers','quotes')`? What is data leakage in this context?\n- A LinearSVC and Logistic Regression give similar accuracy on text. Which would you choose for a production system and why?\n\n---\n**Next →** `13_model_evaluation.ipynb`"),
])

# ===========================================================================
# 13 — MODEL EVALUATION AND SELECTION
# ===========================================================================
save("13_model_evaluation.ipynb", [
    md("# Notebook 13: Model Evaluation and Selection\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Understand why a held-out test set is essential\n- Apply k-fold and stratified cross-validation correctly\n- Choose the right evaluation metric for the task\n- Read and interpret confusion matrices\n- Use ROC-AUC and Precision-Recall curves\n- Tune hyperparameters without data leakage"),
    md("## 1. The Train / Validation / Test Split\n\n| Split | Purpose |\n|-------|---------|\n| **Train** | Fit model parameters |\n| **Validation** | Select hyperparameters / model type |\n| **Test** | Unbiased final performance estimate |\n\n**Golden rule**: the test set must never influence any modelling decision. Once you peek at it, the estimate is biased.\n\n### Cross-Validation\nWith small datasets, a single val split is too noisy. **k-fold CV** gives k estimates:\n1. Split data into k equal folds\n2. For fold i: train on the other k−1 folds, validate on fold i\n3. Average the k scores"),
    code("import numpy as np\nimport matplotlib.pyplot as plt\nfrom sklearn.datasets import load_breast_cancer\nfrom sklearn.model_selection import (\n    train_test_split, StratifiedKFold, cross_val_score,\n    GridSearchCV, learning_curve\n)\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.metrics import (\n    accuracy_score, precision_score, recall_score, f1_score,\n    confusion_matrix, roc_curve, auc,\n    precision_recall_curve, average_precision_score,\n    classification_report\n)\nimport warnings; warnings.filterwarnings('ignore')\n\ncancer = load_breast_cancer()\nX, y = cancer.data, cancer.target\nX_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)\nprint(f'Train: {X_tr.shape}, Test: {X_te.shape}')"),
    code("pipe = Pipeline([('scaler', StandardScaler()), ('clf', LogisticRegression(max_iter=1000))])\n\nskf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\nscores = cross_val_score(pipe, X_tr, y_tr, cv=skf, scoring='accuracy')\nprint('5-fold CV scores:', scores.round(4))\nprint(f'Mean: {scores.mean():.4f} ± {scores.std():.4f}')"),
    md("## 2. Classification Metrics\n\nAccuracy is not always the right metric.\n\n**Imbalanced example**: 99% of transactions are non-fraudulent. A classifier that always says \"not fraud\" gets 99% accuracy but is useless.\n\n| Metric | Formula | Use when |\n|--------|---------|----------|\n| **Accuracy** | (TP+TN)/(P+N) | Balanced classes |\n| **Precision** | TP/(TP+FP) | FP cost is high (spam filter) |\n| **Recall** | TP/(TP+FN) | FN cost is high (cancer screening) |\n| **F1** | 2·P·R/(P+R) | Need balance of P and R |\n| **ROC-AUC** | Area under ROC curve | Ranking quality across thresholds |"),
    code("pipe.fit(X_tr, y_tr)\ny_pred = pipe.predict(X_te)\ny_prob = pipe.predict_proba(X_te)[:, 1]\n\nprint(f'Accuracy : {accuracy_score(y_te, y_pred):.4f}')\nprint(f'Precision: {precision_score(y_te, y_pred):.4f}')\nprint(f'Recall   : {recall_score(y_te, y_pred):.4f}')\nprint(f'F1       : {f1_score(y_te, y_pred):.4f}')\nprint()\nprint(classification_report(y_te, y_pred, target_names=cancer.target_names))"),
    code("cm = confusion_matrix(y_te, y_pred)\ntn, fp, fn, tp = cm.ravel()\n\nfig, axes = plt.subplots(1, 2, figsize=(13, 5))\n\nim = axes[0].imshow(cm, cmap='Blues')\naxes[0].set_xticks([0,1]); axes[0].set_xticklabels(cancer.target_names)\naxes[0].set_yticks([0,1]); axes[0].set_yticklabels(cancer.target_names)\naxes[0].set_xlabel('Predicted'); axes[0].set_ylabel('Actual')\naxes[0].set_title('Confusion Matrix')\nfor i in range(2):\n    for j in range(2):\n        lbl = ['TN','FP','FN','TP'][i*2+j]\n        axes[0].text(j, i, f'{lbl}\\n{cm[i,j]}', ha='center', va='center',\n                     color='white' if cm[i,j]>cm.max()/2 else 'black', fontsize=11)\n\nfpr, tpr, _ = roc_curve(y_te, y_prob)\nroc_auc = auc(fpr, tpr)\naxes[1].plot(fpr, tpr, linewidth=2, label=f'Logistic Reg (AUC={roc_auc:.3f})')\naxes[1].plot([0,1],[0,1], 'k--', alpha=0.4)\naxes[1].set_xlabel('False Positive Rate'); axes[1].set_ylabel('True Positive Rate')\naxes[1].set_title('ROC Curve'); axes[1].legend()\nplt.tight_layout(); plt.show()"),
    md("## 3. Precision-Recall Curve\n\nFor highly imbalanced classes, ROC can be misleadingly optimistic. The **Precision-Recall curve** gives a clearer picture."),
    code("precisions, recalls, thresholds = precision_recall_curve(y_te, y_prob)\navg_prec = average_precision_score(y_te, y_prob)\n\nfig, axes = plt.subplots(1, 2, figsize=(13, 4))\naxes[0].plot(recalls, precisions, linewidth=2)\naxes[0].set_xlabel('Recall'); axes[0].set_ylabel('Precision')\naxes[0].set_title(f'Precision-Recall (AP={avg_prec:.3f})')\n\naxes[1].plot(thresholds, precisions[:-1], label='Precision')\naxes[1].plot(thresholds, recalls[:-1],    label='Recall')\naxes[1].axvline(0.5, color='red', linestyle='--', label='threshold=0.5')\naxes[1].set_xlabel('Threshold'); axes[1].set_title('P & R vs Threshold')\naxes[1].legend()\nplt.tight_layout(); plt.show()"),
    md("## 4. Learning Curves — Diagnosing Bias and Variance\n\n- **High bias (underfitting)**: both train and val error are high\n- **High variance (overfitting)**: train error is low, large gap to val error\n- **Good fit**: both converge to low error with enough data"),
    code("def plot_learning_curve(model, X, y, title, ax):\n    sizes, tr_scores, val_scores = learning_curve(\n        model, X, y, cv=5, train_sizes=np.linspace(0.1, 1.0, 10),\n        scoring='accuracy', n_jobs=-1\n    )\n    ax.plot(sizes, tr_scores.mean(1),  marker='o', label='Train')\n    ax.plot(sizes, val_scores.mean(1), marker='s', label='Validation')\n    ax.fill_between(sizes, tr_scores.mean(1)-tr_scores.std(1),\n                           tr_scores.mean(1)+tr_scores.std(1), alpha=0.15)\n    ax.fill_between(sizes, val_scores.mean(1)-val_scores.std(1),\n                           val_scores.mean(1)+val_scores.std(1), alpha=0.15)\n    ax.set_xlabel('Training samples'); ax.set_ylabel('Accuracy')\n    ax.set_title(title); ax.legend()\n\nfig, axes = plt.subplots(1, 2, figsize=(13, 4))\nplot_learning_curve(\n    Pipeline([('sc', StandardScaler()), ('lr', LogisticRegression(max_iter=1000))]),\n    X, y, 'Logistic Regression', axes[0])\nplot_learning_curve(\n    DecisionTreeClassifier(max_depth=None),\n    X, y, 'Unconstrained Decision Tree', axes[1])\nplt.tight_layout(); plt.show()"),
    md("## 5. Hyperparameter Tuning with GridSearchCV"),
    code("param_grid = {\n    'clf__C'       : [0.001, 0.01, 0.1, 1, 10],\n    'clf__penalty' : ['l1', 'l2'],\n}\npipe_lr = Pipeline([('sc', StandardScaler()),\n                     ('clf', LogisticRegression(max_iter=1000, solver='liblinear'))])\ngrid = GridSearchCV(pipe_lr, param_grid, cv=5, scoring='f1', n_jobs=-1)\ngrid.fit(X_tr, y_tr)\n\nprint(f'Best params: {grid.best_params_}')\nprint(f'Best CV F1 : {grid.best_score_:.4f}')\nprint(f'Test F1    : {f1_score(y_te, grid.best_estimator_.predict(X_te)):.4f}')"),
    md("## Exercises\n\n1. Create a synthetic imbalanced dataset (95% class 0, 5% class 1). Compare Accuracy, F1, and ROC-AUC. Which is most informative?\n2. Use `RandomizedSearchCV` instead of `GridSearchCV` on a Random Forest. Is it faster? Does it find a comparable result?\n3. Plot ROC curves for four classifiers on the same axes. Which model dominates?\n4. Implement **nested cross-validation** (outer loop for performance estimation, inner loop for tuning). When is this necessary?\n\n## Reflection Questions\n- You tune hyperparameters on the validation fold and then report test performance. Is this estimate still unbiased? Why?\n- What does ROC-AUC = 0.5 mean? What about 1.0?\n- Precision and Recall trade off against each other. In a spam filter, which matters more? In a cancer screening test?\n\n---\n**Next →** `14_clustering.ipynb`"),
])

# ===========================================================================
# 14 — CLUSTERING
# ===========================================================================
save("14_clustering.ipynb", [
    md("# Notebook 14: Clustering — Unsupervised Learning\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Distinguish supervised from unsupervised learning\n- Apply K-Means and choose K with Elbow and Silhouette methods\n- Build and read a dendrogram for hierarchical clustering\n- Apply DBSCAN to find clusters of arbitrary shape\n- Evaluate clustering quality with appropriate metrics"),
    md("## 1. What Is Clustering?\n\nIn **unsupervised learning** there are no labels — we want to discover structure in the data.\n\n**Clustering** groups similar data points together. Applications:\n- Customer segmentation\n- Document grouping\n- Anomaly detection\n- Gene expression analysis\n- Image compression\n\n**Key challenge**: we have no ground truth to validate against directly."),
    code("import numpy as np\nimport matplotlib.pyplot as plt\nfrom sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN\nfrom sklearn.datasets import make_blobs, make_moons, make_circles, load_iris\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.metrics import silhouette_score, adjusted_rand_score\nfrom scipy.cluster.hierarchy import dendrogram, linkage\nimport warnings; warnings.filterwarnings('ignore')\nnp.random.seed(42)"),
    md("## 2. K-Means\n\n**Algorithm**:\n1. Choose K initial centroids (K-Means++ initialisation)\n2. Assign each point to its nearest centroid\n3. Recompute each centroid as the mean of its assigned points\n4. Repeat 2–3 until convergence\n\n**Objective**: minimise within-cluster sum of squares (WCSS / inertia):\n$$\\text{WCSS} = \\sum_{k=1}^K \\sum_{\\mathbf{x} \\in C_k} \\|\\mathbf{x} - \\boldsymbol{\\mu}_k\\|^2$$"),
    code("X_blob, y_true = make_blobs(n_samples=300, centers=4, cluster_std=0.8, random_state=42)\nkm = KMeans(n_clusters=4, init='k-means++', n_init=10, random_state=42)\nlabels = km.fit_predict(X_blob)\n\nfig, axes = plt.subplots(1, 2, figsize=(13, 4))\naxes[0].scatter(X_blob[:,0], X_blob[:,1], c=y_true, cmap='Set1', s=30, alpha=0.7)\naxes[0].set_title('True Clusters')\n\naxes[1].scatter(X_blob[:,0], X_blob[:,1], c=labels, cmap='Set1', s=30, alpha=0.7)\naxes[1].scatter(km.cluster_centers_[:,0], km.cluster_centers_[:,1],\n                marker='*', s=400, c='black', zorder=5, label='Centroids')\naxes[1].set_title(f'K-Means  ARI={adjusted_rand_score(y_true, labels):.3f}')\naxes[1].legend()\nplt.tight_layout(); plt.show()"),
    md("## 3. Choosing K — Elbow and Silhouette\n\n**Elbow**: plot WCSS vs K — look for where the curve bends.\n\n**Silhouette score** $s$ for a point:\n$$s = \\frac{b - a}{\\max(a, b)}$$\nwhere $a$ = average distance to same-cluster points, $b$ = average distance to nearest other-cluster points.\n$s \\in [-1, 1]$: higher = better clustering."),
    code("inertias, silhouettes = [], []\nfor k in range(2, 11):\n    km_k = KMeans(n_clusters=k, init='k-means++', n_init=10, random_state=42)\n    lbl = km_k.fit_predict(X_blob)\n    inertias.append(km_k.inertia_)\n    silhouettes.append(silhouette_score(X_blob, lbl))\n\nbest_k = np.argmax(silhouettes) + 2\nfig, axes = plt.subplots(1, 2, figsize=(13, 4))\naxes[0].plot(range(2,11), inertias, marker='o')\naxes[0].set_xlabel('K'); axes[0].set_ylabel('WCSS'); axes[0].set_title('Elbow Method')\naxes[1].plot(range(2,11), silhouettes, marker='s', color='darkorange')\naxes[1].axvline(best_k, color='red', linestyle='--', label=f'Best K={best_k}')\naxes[1].set_xlabel('K'); axes[1].set_ylabel('Silhouette')\naxes[1].set_title('Silhouette Score'); axes[1].legend()\nplt.tight_layout(); plt.show()\nprint(f'Best K by silhouette: {best_k}')"),
    md("## 4. Hierarchical Clustering\n\n**Agglomerative** (bottom-up):\n1. Each point is its own cluster\n2. Merge the two closest clusters\n3. Repeat until one cluster remains\n\nThe **dendrogram** visualises the merge history. Cut at any height to get a flat clustering."),
    code("X_hier, _ = make_blobs(n_samples=40, centers=4, cluster_std=0.6, random_state=1)\nZ = linkage(X_hier, method='ward')\n\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\ndendrogram(Z, ax=axes[0], leaf_rotation=90, color_threshold=4)\naxes[0].axhline(4, color='red', linestyle='--', label='Cut → 4 clusters')\naxes[0].set_title('Dendrogram (Ward linkage)')\naxes[0].set_xlabel('Sample'); axes[0].set_ylabel('Distance')\naxes[0].legend()\n\nag = AgglomerativeClustering(n_clusters=4, linkage='ward')\naxes[1].scatter(X_hier[:,0], X_hier[:,1], c=ag.fit_predict(X_hier), cmap='Set1', s=60)\naxes[1].set_title('Agglomerative Clustering (K=4)')\nplt.tight_layout(); plt.show()"),
    md("## 5. DBSCAN — Density-Based Clustering\n\nDBSCAN finds clusters of **arbitrary shape** based on local density:\n- **Core point**: ≥ `min_samples` neighbours within radius `eps`\n- **Border point**: within `eps` of a core point\n- **Noise point**: neither → labelled −1 (outlier)\n\n**Advantages**: no need to specify K; finds non-convex clusters; identifies outliers automatically."),
    code("X_moon, _ = make_moons(n_samples=300, noise=0.07, random_state=42)\nX_circ, _ = make_circles(n_samples=300, noise=0.05, factor=0.5, random_state=42)\n\nfig, axes = plt.subplots(2, 3, figsize=(15, 8))\nfor row, (X_d, name) in enumerate([(X_moon,'Moons'),(X_circ,'Circles')]):\n    for col, (alg, lbl) in enumerate([\n        (KMeans(n_clusters=2, random_state=42),           'K-Means'),\n        (AgglomerativeClustering(n_clusters=2),            'Agglomerative'),\n        (DBSCAN(eps=0.2, min_samples=5),                   'DBSCAN'),\n    ]):\n        ax = axes[row][col]\n        preds = alg.fit_predict(X_d)\n        ax.scatter(X_d[:,0], X_d[:,1], c=preds, cmap='Set1', s=15, alpha=0.8)\n        noise = (preds==-1).sum() if hasattr(alg,'labels_') and -1 in preds else 0\n        ax.set_title(f'{name}: {lbl}' + (f' (noise={noise})' if noise else ''))\n        ax.set_xticks([]); ax.set_yticks([])\nplt.tight_layout(); plt.show()"),
    md("## Exercises\n\n1. Apply K-Means to the Iris dataset (without labels). Does the Silhouette score suggest K=3 (the true number of species)? Measure ARI.\n2. Try `linkage='single'`, `'complete'`, `'average'`, and `'ward'`. Which produces the most compact clusters?\n3. For the moons dataset, vary `eps = [0.05, 0.1, 0.2, 0.5]`. What happens when eps is too small? Too large?\n4. Apply PCA (2 components) to the breast cancer dataset, cluster with K-Means (K=2), and visualise. Do clusters align with benign/malignant?\n\n## Reflection Questions\n- K-Means assumes spherical, equal-sized clusters. Give two real-world examples where this assumption fails badly.\n- Why must you scale features before K-Means but not before a tree-based method?\n- If you cluster customers and one cluster is labelled \"high-value,\" what ethical issues arise from automated decisions based on this?\n\n---\n**Next →** `15_deep_learning_foundations.ipynb`"),
])

# ===========================================================================
# 15 — DEEP LEARNING FOUNDATIONS
# ===========================================================================
save("15_deep_learning_foundations.ipynb", [
    md("# Notebook 15: Deep Learning Foundations\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Implement a perceptron from scratch and understand its limits\n- Explain and visualise common activation functions\n- Trace a forward pass through a multi-layer network\n- Implement backpropagation manually on a tiny network\n- Know where deep learning excels over classical ML"),
    md("## 1. The Perceptron\n\nArtificial neurons are inspired by biological ones. A **perceptron**:\n1. Receives inputs $x_1, \\ldots, x_n$ with weights $w_i$\n2. Computes weighted sum + bias: $z = \\sum w_i x_i + b$\n3. Applies a step function: $\\hat{y} = 1$ if $z \\geq 0$ else $0$\n\nThe **perceptron learning rule**:\n$$w_i \\leftarrow w_i + \\eta (y - \\hat{y}) x_i$$\nIf the prediction is correct, weights don't change. If wrong, they update to push $z$ in the right direction."),
    code("import numpy as np\nimport matplotlib.pyplot as plt\nimport warnings; warnings.filterwarnings('ignore')\nnp.random.seed(42)\n\nclass Perceptron:\n    def __init__(self, lr=0.1, n_epochs=50):\n        self.lr = lr; self.n_epochs = n_epochs\n\n    def fit(self, X, y):\n        self.w = np.zeros(X.shape[1])\n        self.b = 0.0\n        self.errors = []\n        for _ in range(self.n_epochs):\n            errs = 0\n            for xi, yi in zip(X, y):\n                pred = self._predict(xi)\n                update = self.lr * (yi - pred)\n                self.w += update * xi\n                self.b += update\n                errs += int(update != 0)\n            self.errors.append(errs)\n\n    def _predict(self, x): return 1 if np.dot(self.w, x) + self.b >= 0 else 0\n    def predict(self, X): return np.array([self._predict(x) for x in X])\n\n# AND gate\nX_and = np.array([[0,0],[0,1],[1,0],[1,1]], dtype=float)\ny_and = np.array([0, 0, 0, 1])\n\np = Perceptron(lr=0.1, n_epochs=20)\np.fit(X_and, y_and)\nprint('AND gate predictions:')\nfor xi, yi in zip(X_and, y_and):\n    pred = p._predict(xi)\n    print(f'  {xi.astype(int)} → pred={pred}, true={yi} {\"✓\" if pred==yi else \"✗\"}')\n\nfig, ax = plt.subplots(figsize=(7,3))\nax.plot(p.errors, marker='o')\nax.set_xlabel('Epoch'); ax.set_ylabel('Misclassifications')\nax.set_title('Perceptron Learning Curve (AND gate)')\nplt.tight_layout(); plt.show()"),
    md("## 2. The XOR Problem — Why We Need Multiple Layers\n\nA single perceptron can only learn **linearly separable** functions. XOR is the classic counter-example.\n\nMinsky & Papert (1969) proved this limitation, leading to the first AI Winter. The solution: **Multi-Layer Perceptrons (MLP)** trained with backpropagation."),
    code("X_xor = np.array([[0,0],[0,1],[1,0],[1,1]], dtype=float)\ny_xor = np.array([0, 1, 1, 0])\n\np_xor = Perceptron(lr=0.1, n_epochs=100)\np_xor.fit(X_xor, y_xor)\nprint('XOR — perceptron still fails:')\nfor xi, yi, pred in zip(X_xor, y_xor, p_xor.predict(X_xor)):\n    print(f'  {xi.astype(int)} → pred={pred}, true={yi} {\"✓\" if pred==yi else \"✗\"}')\nprint(f'Final errors: {p_xor.errors[-1]} (should be > 0)')"),
    md("## 3. Activation Functions\n\nActivation functions introduce **non-linearity**. Without them, stacking layers collapses to a single linear transformation.\n\n| Function | Formula | Range | Common use |\n|----------|---------|-------|------------|\n| **Sigmoid** | $1/(1+e^{-z})$ | (0,1) | Binary output |\n| **Tanh** | $(e^z-e^{-z})/(e^z+e^{-z})$ | (-1,1) | Older hidden layers |\n| **ReLU** | $\\max(0,z)$ | $[0,\\infty)$ | Default hidden layer |\n| **Leaky ReLU** | $\\max(0.01z, z)$ | $\\mathbb{R}$ | Fixes dying ReLU |\n| **Softmax** | $e^{z_k}/\\sum e^{z_j}$ | $(0,1)$ | Multiclass output |"),
    code("z = np.linspace(-5, 5, 300)\nactivations = {\n    'Sigmoid'    : 1/(1+np.exp(-z)),\n    'Tanh'       : np.tanh(z),\n    'ReLU'       : np.maximum(0, z),\n    'Leaky ReLU' : np.where(z>=0, z, 0.01*z),\n    'Swish'      : z/(1+np.exp(-z)),\n}\nfig, axes = plt.subplots(1, 5, figsize=(18, 3))\nfor ax, (name, fz) in zip(axes, activations.items()):\n    ax.plot(z, fz, linewidth=2)\n    ax.axhline(0, color='gray', linewidth=0.5)\n    ax.axvline(0, color='gray', linewidth=0.5)\n    ax.set_title(name); ax.set_xlabel('z')\nplt.suptitle('Activation Functions')\nplt.tight_layout(); plt.show()"),
    md("## 4. Multi-Layer Perceptron — Forward Pass\n\nStack layers: Input → Hidden(s) → Output\n\n$$\\mathbf{a}^{(1)} = \\text{ReLU}(W^{(1)}\\mathbf{x} + \\mathbf{b}^{(1)})$$\n$$\\mathbf{a}^{(2)} = \\text{ReLU}(W^{(2)}\\mathbf{a}^{(1)} + \\mathbf{b}^{(2)})$$\n$$\\hat{y} = \\sigma(W^{(3)}\\mathbf{a}^{(2)} + b^{(3)})$$"),
    code("def relu(z): return np.maximum(0, z)\ndef softmax(z): e=np.exp(z-z.max()); return e/e.sum()\n\nnp.random.seed(1)\nW1 = np.random.randn(4,3)*0.5; b1 = np.zeros(4)\nW2 = np.random.randn(4,4)*0.5; b2 = np.zeros(4)\nW3 = np.random.randn(2,4)*0.5; b3 = np.zeros(2)\n\ndef forward(x):\n    a1 = relu(W1 @ x + b1)\n    a2 = relu(W2 @ a1 + b2)\n    out = softmax(W3 @ a2 + b3)\n    return out, a1, a2\n\nxin = np.array([1.0, -0.5, 2.0])\nout, a1, a2 = forward(xin)\nprint('Input        :', xin)\nprint('Hidden 1 act :', a1.round(3))\nprint('Hidden 2 act :', a2.round(3))\nprint('Output probs :', out.round(3))\nprint('Predicted    :', np.argmax(out))"),
    md("## 5. Backpropagation — Learning Weights\n\n**Backpropagation** applies the **chain rule** to propagate gradients from output back to each weight:\n\n$$\\frac{\\partial L}{\\partial W^{(1)}} = \\frac{\\partial L}{\\partial \\hat{y}} \\cdot \\frac{\\partial \\hat{y}}{\\partial a^{(2)}} \\cdot \\frac{\\partial a^{(2)}}{\\partial a^{(1)}} \\cdot \\frac{\\partial a^{(1)}}{\\partial W^{(1)}}$$\n\nModern frameworks (PyTorch, TensorFlow) compute this automatically via **autograd**."),
    code("# Manual backprop on XOR — 2-in, 2-hidden, 1-out MLP\ndef sigmoid(z): return 1/(1+np.exp(-z))\ndef sigmoid_d(a): return a*(1-a)\ndef bce(y, yh): return -np.mean(y*np.log(yh+1e-8)+(1-y)*np.log(1-yh+1e-8))\n\nX = np.array([[0,0],[0,1],[1,0],[1,1]], dtype=float)\ny = np.array([[0],[1],[1],[0]], dtype=float)\n\nnp.random.seed(1)\nW1 = np.random.randn(2,2)*0.5; b1 = np.zeros((1,2))\nW2 = np.random.randn(2,1)*0.5; b2 = np.zeros((1,1))\nlr = 0.5; hist = []\n\nfor epoch in range(5000):\n    a1 = sigmoid(X @ W1 + b1)\n    a2 = sigmoid(a1 @ W2 + b2)\n    d2 = (a2-y)*sigmoid_d(a2)\n    W2 -= lr * a1.T @ d2;  b2 -= lr * d2.mean(0)\n    d1 = (d2 @ W2.T)*sigmoid_d(a1)\n    W1 -= lr * X.T @ d1;   b1 -= lr * d1.mean(0)\n    if epoch % 100 == 0: hist.append(bce(y, a2))\n\nprint('XOR after training:')\nfor xi, yi, pi in zip(X, y, a2):\n    print(f'  {xi.astype(int)} → p={pi[0]:.3f}, pred={int(pi[0]>0.5)}, true={int(yi[0])}')\n\nfig, ax = plt.subplots(figsize=(8,3))\nax.plot(hist)\nax.set_xlabel('100-epoch intervals'); ax.set_ylabel('Loss')\nax.set_title('MLP Solving XOR via Backpropagation')\nplt.tight_layout(); plt.show()"),
    md("## Exercises\n\n1. Modify the Perceptron to learn the OR gate. How many epochs does it need?\n2. Add a momentum term to the backprop network. Does it converge faster?\n3. Plot the decision boundary of the trained XOR network by evaluating it on a 2D grid.\n4. Prove algebraically that stacking two linear layers (no activation) is equivalent to a single linear layer.\n\n## Reflection Questions\n- What is the \"dying ReLU\" problem, and how does Leaky ReLU address it?\n- Backpropagation requires differentiable activations. How do we handle ReLU, which is non-differentiable at z=0?\n- Deep learning models have millions of parameters. Why don't they always overfit?\n\n---\n**Next →** `16_pytorch_basics.ipynb`"),
])

# ===========================================================================
# 16 — PYTORCH BASICS
# ===========================================================================
save("16_pytorch_basics.ipynb", [
    md("# Notebook 16: PyTorch Basics\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Create and manipulate PyTorch tensors\n- Understand automatic differentiation (autograd)\n- Build a neural network using `nn.Module`\n- Write a complete training loop\n- Use `Dataset` and `DataLoader` for batched training"),
    md("## 1. Why PyTorch?\n\n- **Dynamic computation graph**: builds the graph on-the-fly → easy debugging\n- **Autograd**: automatic gradient computation for any tensor expression\n- **GPU support**: move tensors with `.to(device)` — same code runs on CPU or GPU\n- **Pythonic**: feels like NumPy, integrates with the whole Python ecosystem\n- **Ecosystem**: HuggingFace, torchvision, Lightning all built on top"),
    code("import torch\nimport torch.nn as nn\nimport torch.optim as optim\nfrom torch.utils.data import TensorDataset, DataLoader\nimport numpy as np\nimport matplotlib.pyplot as plt\n\nprint(f'PyTorch version: {torch.__version__}')\ndevice = 'cuda' if torch.cuda.is_available() else 'cpu'\nprint(f'Using device  : {device}')"),
    md("## 2. Tensors"),
    code("# Creating tensors\nt1 = torch.tensor([1.0, 2.0, 3.0])\nt2 = torch.zeros(3, 4)\nt3 = torch.randn(2, 3)\nt4 = torch.arange(0, 10, 2, dtype=torch.float32)\n\nprint('t1:', t1)\nprint('t2 shape:', t2.shape)\nprint('t3:\\n', t3)\nprint('t4:', t4)\n\n# Interoperability with NumPy\nnp_arr = np.array([1.0, 2.0, 3.0])\nt_from_np = torch.from_numpy(np_arr)\nprint('\\nFrom NumPy:', t_from_np)\nprint('Back to NumPy:', t1.numpy())"),
    code("# Operations\na = torch.tensor([[1.,2.],[3.,4.]])\nb = torch.tensor([[5.,6.],[7.,8.]])\nprint('Element-wise *:\\n', a * b)\nprint('Matrix mult @:\\n', a @ b)\nprint('Mean:', a.mean(), ' Sum:', a.sum())\n\n# Broadcasting\nc = torch.tensor([10., 20.])\nprint('Broadcast + c (adds to each row):\\n', a + c)"),
    md("## 3. Autograd — Automatic Differentiation"),
    code("# Simple: y = 3x² + 2x + 1, dy/dx = 6x + 2\nx = torch.tensor(2.0, requires_grad=True)\ny = 3*x**2 + 2*x + 1\ny.backward()\nprint(f'x={x.item()}, y={y.item()}, dy/dx={x.grad.item()}  (expected {6*2+2})')"),
    code("# Multi-parameter gradient\ntorch.manual_seed(42)\nw = torch.randn(3, requires_grad=True)\nb = torch.zeros(1, requires_grad=True)\n\nX_d = torch.randn(100, 3)\ny_d = X_d @ torch.tensor([1.0, -2.0, 0.5]) + 0.3\n\ny_pred = X_d @ w + b\nloss = ((y_pred - y_d)**2).mean()\nloss.backward()\n\nprint(f'Loss: {loss.item():.4f}')\nprint(f'dL/dw: {w.grad}')\nprint(f'dL/db: {b.grad}')"),
    md("## 4. Building a Network with nn.Module"),
    code("class MLP(nn.Module):\n    def __init__(self, input_dim, hidden_dim, output_dim):\n        super().__init__()\n        self.net = nn.Sequential(\n            nn.Linear(input_dim, hidden_dim),\n            nn.ReLU(),\n            nn.Linear(hidden_dim, hidden_dim),\n            nn.ReLU(),\n            nn.Linear(hidden_dim, output_dim),\n        )\n    def forward(self, x): return self.net(x)\n\nmodel = MLP(8, 64, 1)\nprint(model)\nprint(f'\\nTotal parameters: {sum(p.numel() for p in model.parameters()):,}')"),
    md("## 5. The Training Loop"),
    code("from sklearn.datasets import load_breast_cancer\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.model_selection import train_test_split\n\ncancer = load_breast_cancer()\nX_np = StandardScaler().fit_transform(cancer.data.astype(np.float32))\ny_np = cancer.target.astype(np.float32)\n\nX_tr, X_te, y_tr, y_te = train_test_split(X_np, y_np, test_size=0.2, random_state=42)\n\nX_train_t = torch.tensor(X_tr);  y_train_t = torch.tensor(y_tr).unsqueeze(1)\nX_test_t  = torch.tensor(X_te);  y_test_t  = torch.tensor(y_te).unsqueeze(1)\n\ntrain_dl = DataLoader(TensorDataset(X_train_t, y_train_t), batch_size=32, shuffle=True)\n\nmodel = MLP(30, 64, 1).to(device)\ncriterion = nn.BCEWithLogitsLoss()\noptimizer = optim.Adam(model.parameters(), lr=1e-3)\n\ntrain_losses, val_losses = [], []\nfor epoch in range(100):\n    model.train()\n    ep_loss = 0\n    for Xb, yb in train_dl:\n        Xb, yb = Xb.to(device), yb.to(device)\n        optimizer.zero_grad()\n        loss = criterion(model(Xb), yb)\n        loss.backward()\n        optimizer.step()\n        ep_loss += loss.item()\n    train_losses.append(ep_loss / len(train_dl))\n\n    model.eval()\n    with torch.no_grad():\n        v = criterion(model(X_test_t.to(device)), y_test_t.to(device)).item()\n    val_losses.append(v)\n\nmodel.eval()\nwith torch.no_grad():\n    preds = (torch.sigmoid(model(X_test_t.to(device))) > 0.5).float()\n    acc = (preds == y_test_t.to(device)).float().mean()\nprint(f'Test Accuracy: {acc.item():.4f}')"),
    code("fig, ax = plt.subplots(figsize=(9, 4))\nax.plot(train_losses, label='Train')\nax.plot(val_losses,   label='Validation')\nax.set_xlabel('Epoch'); ax.set_ylabel('BCE Loss')\nax.set_title('Training and Validation Loss')\nax.legend()\nplt.tight_layout(); plt.show()"),
    md("## 6. Regularisation Techniques"),
    code("class BetterMLP(nn.Module):\n    def __init__(self, input_dim):\n        super().__init__()\n        self.net = nn.Sequential(\n            nn.Linear(input_dim, 128),\n            nn.BatchNorm1d(128),\n            nn.ReLU(),\n            nn.Dropout(0.3),\n            nn.Linear(128, 64),\n            nn.BatchNorm1d(64),\n            nn.ReLU(),\n            nn.Dropout(0.3),\n            nn.Linear(64, 1)\n        )\n    def forward(self, x): return self.net(x)\n\nbm = BetterMLP(30)\nprint(bm)\nprint(f'Parameters: {sum(p.numel() for p in bm.parameters()):,}')"),
    md("## Exercises\n\n1. Add a `StepLR` learning rate scheduler that drops the LR by 0.5 every 30 epochs. Does it improve final accuracy?\n2. Implement **early stopping**: stop training if val loss doesn't improve for 10 consecutive epochs.\n3. Change the MLP to output 3 classes and train on the Iris dataset. Use `CrossEntropyLoss`.\n4. Time training on CPU vs GPU (if available). At what batch size does GPU become faster?\n\n## Reflection Questions\n- Why must `optimizer.zero_grad()` be called before each backward pass?\n- What is the difference between `BCELoss` and `BCEWithLogitsLoss`? Which is numerically more stable?\n- Why do `BatchNorm` and `Dropout` behave differently during training vs evaluation?\n\n---\n**Next →** `17_cnn_rnn_lstm.ipynb`"),
])

# ===========================================================================
# 17 — CNN, RNN, LSTM
# ===========================================================================
save("17_cnn_rnn_lstm.ipynb", [
    md("# Notebook 17: CNNs, RNNs, and LSTMs\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Understand convolutional layers and why they suit images\n- Build and train a CNN on MNIST\n- Explain the vanishing gradient problem in plain RNNs\n- Understand LSTM gating mechanisms\n- Apply an LSTM to a sequence classification task"),
    md("## Part A — Convolutional Neural Networks (CNN)\n\n## 1. Why Not MLP for Images?\n\n- A 28×28 image = 784 pixels; 100 hidden units → 78,400 parameters per layer\n- **No spatial awareness**: shuffling pixels randomly leaves accuracy unchanged\n- **Not translation invariant**: a cat in the corner vs the centre look completely different\n\n## 2. Convolutional Layer\n\nA **filter (kernel)** slides across the image computing dot products at each position:\n- **Parameter sharing**: same filter applied everywhere → far fewer parameters\n- **Translation equivariance**: a feature fires wherever the pattern appears\n- **Stacking conv layers**: early layers detect edges, middle layers detect shapes, deep layers detect objects"),
    code("import torch\nimport torch.nn as nn\nimport torch.optim as optim\nfrom torch.utils.data import DataLoader\nimport torchvision, torchvision.transforms as transforms\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport warnings; warnings.filterwarnings('ignore')\n\ndevice = 'cuda' if torch.cuda.is_available() else 'cpu'\nprint(f'Device: {device}')"),
    code("# Manual 2D convolution to show edge detection\nimport numpy as np\n\nimg = np.zeros((28, 28))\nimg[5:23, 5:10] = 1.0\nimg[5:10, 5:23] = 1.0\n\nvert_k  = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])\nhoriz_k = np.array([[-1,-1,-1],[0,0,0],[1,1,1]])\n\ndef conv2d(img, k):\n    kh, kw = k.shape\n    out = np.zeros((img.shape[0]-kh+1, img.shape[1]-kw+1))\n    for i in range(out.shape[0]):\n        for j in range(out.shape[1]):\n            out[i,j] = (img[i:i+kh, j:j+kw]*k).sum()\n    return out\n\nfig, axes = plt.subplots(1, 3, figsize=(12, 4))\nfor ax, data, title in zip(axes,\n    [img, conv2d(img, vert_k), conv2d(img, horiz_k)],\n    ['Original', 'Vertical edge filter', 'Horizontal edge filter']):\n    ax.imshow(data, cmap='gray'); ax.set_title(title); ax.axis('off')\nplt.tight_layout(); plt.show()"),
    md("## 3. CNN for MNIST"),
    code("transform = transforms.Compose([\n    transforms.ToTensor(),\n    transforms.Normalize((0.1307,), (0.3081,))\n])\ntrain_set = torchvision.datasets.MNIST('./data', train=True,  download=True, transform=transform)\ntest_set  = torchvision.datasets.MNIST('./data', train=False, download=True, transform=transform)\ntrain_dl  = DataLoader(train_set, batch_size=128, shuffle=True)\ntest_dl   = DataLoader(test_set,  batch_size=256, shuffle=False)\nprint(f'Train: {len(train_set)}, Test: {len(test_set)}, Image: {train_set[0][0].shape}')"),
    code("class CNN(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.features = nn.Sequential(\n            nn.Conv2d(1, 32, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),  # 28→14\n            nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2), # 14→7\n        )\n        self.clf = nn.Sequential(\n            nn.Flatten(),\n            nn.Linear(64*7*7, 128), nn.ReLU(), nn.Dropout(0.4),\n            nn.Linear(128, 10)\n        )\n    def forward(self, x): return self.clf(self.features(x))\n\ncnn = CNN().to(device)\nprint(cnn)\nprint(f'Parameters: {sum(p.numel() for p in cnn.parameters()):,}')"),
    code("criterion = nn.CrossEntropyLoss()\noptimizer = optim.Adam(cnn.parameters(), lr=1e-3)\n\ntrain_accs, test_accs = [], []\nfor epoch in range(5):\n    cnn.train()\n    correct = total = 0\n    for X, y in train_dl:\n        X, y = X.to(device), y.to(device)\n        optimizer.zero_grad()\n        out = cnn(X)\n        loss = criterion(out, y)\n        loss.backward(); optimizer.step()\n        correct += (out.argmax(1)==y).sum().item(); total += len(y)\n    train_accs.append(correct/total)\n\n    cnn.eval()\n    correct = total = 0\n    with torch.no_grad():\n        for X, y in test_dl:\n            X, y = X.to(device), y.to(device)\n            correct += (cnn(X).argmax(1)==y).sum().item(); total += len(y)\n    test_accs.append(correct/total)\n    print(f'Epoch {epoch+1}/5 | Train={train_accs[-1]:.4f} | Test={test_accs[-1]:.4f}')"),
    md("## Part B — Recurrent Networks (RNN) and LSTM\n\n## 4. Why RNNs?\n\nLanguage, time series, and audio are **sequential** — order matters.\n\n$$h_t = \\tanh(W_{xh} x_t + W_{hh} h_{t-1} + b)$$\n\nThe hidden state $h_t$ carries information forward. **Problem**: with long sequences, gradients either vanish (exponentially small) or explode (exponentially large) during backpropagation through time.\n\n## 5. LSTM Gates\n\nLSTMs introduce a **cell state** $C_t$ (\"memory highway\") with three gates:\n\n| Gate | Controls |\n|------|----------|\n| **Forget** $f_t = \\sigma(W_f[h_{t-1}, x_t])$ | What to erase from $C$ |\n| **Input** $i_t = \\sigma(W_i[h_{t-1}, x_t])$ | What new info to write |\n| **Output** $o_t = \\sigma(W_o[h_{t-1}, x_t])$ | What to expose as $h_t$ |\n\n$$C_t = f_t \\odot C_{t-1} + i_t \\odot \\tilde{C}_t, \\quad h_t = o_t \\odot \\tanh(C_t)$$"),
    code("# LSTM for sequence classification\n# Positive: upward trend; Negative: downward trend\nnp.random.seed(42); torch.manual_seed(42)\n\ndef make_seq_data(n=1000, L=20):\n    X, y = [], []\n    for _ in range(n):\n        if np.random.rand() > 0.5:\n            seq = np.cumsum(np.random.randn(L)) + np.random.randn(L)*0.3; y.append(1)\n        else:\n            seq = -np.cumsum(np.random.randn(L)) + np.random.randn(L)*0.3; y.append(0)\n        X.append(seq)\n    return (np.array(X, dtype=np.float32),\n            np.array(y, dtype=np.float32))\n\nX_s, y_s = make_seq_data()\nX_tr = torch.tensor(X_s[:800]).unsqueeze(-1)  # (800, 20, 1)\nX_te = torch.tensor(X_s[800:]).unsqueeze(-1)\ny_tr = torch.tensor(y_s[:800]).unsqueeze(1)\ny_te = torch.tensor(y_s[800:]).unsqueeze(1)"),
    code("class LSTMClassifier(nn.Module):\n    def __init__(self, input_size=1, hidden=32, layers=1):\n        super().__init__()\n        self.lstm = nn.LSTM(input_size, hidden, layers, batch_first=True)\n        self.fc   = nn.Linear(hidden, 1)\n    def forward(self, x):\n        out, _ = self.lstm(x)\n        return self.fc(out[:, -1, :])\n\nlstm = LSTMClassifier().to(device)\nopt = optim.Adam(lstm.parameters(), lr=1e-3)\ncrit = nn.BCEWithLogitsLoss()\n\nfrom torch.utils.data import TensorDataset, DataLoader\ndl = DataLoader(TensorDataset(X_tr, y_tr), batch_size=64, shuffle=True)\n\nfor epoch in range(30):\n    lstm.train()\n    tot = 0\n    for Xb, yb in dl:\n        Xb, yb = Xb.to(device), yb.to(device)\n        opt.zero_grad()\n        l = crit(lstm(Xb), yb)\n        l.backward(); opt.step()\n        tot += l.item()\n    if (epoch+1) % 10 == 0:\n        print(f'Epoch {epoch+1:3d} | Loss: {tot/len(dl):.4f}')\n\nlstm.eval()\nwith torch.no_grad():\n    preds = (torch.sigmoid(lstm(X_te.to(device))) > 0.5).float()\n    acc = (preds == y_te.to(device)).float().mean()\nprint(f'Test Accuracy: {acc.item():.4f}')"),
    md("## Exercises\n\n1. Visualise the 32 feature maps from the first conv layer for a test image. What patterns do they detect?\n2. Add a third conv block. Does it improve MNIST accuracy? At what cost?\n3. Replace the LSTM with a GRU (`nn.GRU`). Compare parameters, speed, and accuracy.\n4. Use a bidirectional LSTM (`bidirectional=True`). Does it help for the sequence classification task?\n\n## Reflection Questions\n- Max pooling reduces spatial size. What information is preserved? What is lost?\n- An RNN uses the same weight matrix at every time step. Why is this both a strength and a weakness?\n- Why do LSTM gates help with the vanishing gradient problem? (Hint: think about what the forget gate does to the gradient.)\n\n---\n**Next →** `18_stock_prediction_lstm.ipynb`"),
])

# ===========================================================================
# 18 — STOCK PREDICTION WITH LSTM
# ===========================================================================
save("18_stock_prediction_lstm.ipynb", [
    md("# Notebook 18: Stock Market Prediction with LSTM\n**DCS 404 — Data Science and Machine Learning**\n\n---\n\n## Learning Objectives\n- Understand time series forecasting and its unique challenges\n- Prepare a sliding-window dataset for sequence prediction\n- Build and train an LSTM for one-step-ahead forecasting\n- Evaluate with MAE, RMSE, and directional accuracy\n- Critically assess the limits of ML-based stock prediction\n\n> **Disclaimer**: This notebook is purely educational. No investment advice is implied."),
    md("## 1. Time Series vs Standard ML\n\n| | Standard ML | Time Series |\n|--|-------------|-------------|\n| Sample order | Irrelevant | Critical |\n| Train/test split | Random shuffle ok | Chronological only |\n| Features | Given | Often lag-engineered |\n| Target | Fixed label | Future values |\n\n**The sliding window**: convert a sequence into supervised learning examples:\n```\nSequence: [p1, p2, p3, p4, p5, p6, ...]\nWindow=3:   X=[p1,p2,p3] → y=p4\n            X=[p2,p3,p4] → y=p5\n            X=[p3,p4,p5] → y=p6\n```"),
    code("import numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport torch\nimport torch.nn as nn\nimport torch.optim as optim\nfrom torch.utils.data import TensorDataset, DataLoader\nfrom sklearn.preprocessing import MinMaxScaler\nfrom sklearn.metrics import mean_absolute_error, mean_squared_error\nimport warnings; warnings.filterwarnings('ignore')\n\ntorch.manual_seed(42); np.random.seed(42)\ndevice = 'cuda' if torch.cuda.is_available() else 'cpu'\nprint(f'Device: {device}')"),
    md("## 2. Synthetic Stock Data (Geometric Brownian Motion)\n\n$$S_t = S_{t-1} \\cdot \\exp\\left[(\\mu - \\tfrac{\\sigma^2}{2})\\Delta t + \\sigma\\sqrt{\\Delta t}\\,\\epsilon_t\\right], \\quad \\epsilon_t \\sim \\mathcal{N}(0,1)$$\n\nThis is the continuous-time model underpinning Black-Scholes option pricing. It produces realistic-looking price series."),
    code("def gbm(S0=100, mu=0.0003, sigma=0.018, T=1200):\n    prices = [S0]\n    for _ in range(T-1):\n        prices.append(prices[-1] * np.exp((mu - 0.5*sigma**2) + sigma*np.random.randn()))\n    return np.array(prices)\n\nprices = gbm()\ndates = pd.date_range('2019-01-01', periods=1200, freq='B')\ndf = pd.DataFrame({'Price': prices}, index=dates)\n\nfig, ax = plt.subplots(figsize=(12, 4))\nax.plot(df.index, df['Price'], color='steelblue')\nax.set_title('Simulated Stock Price (GBM)')\nax.set_ylabel('Price ($)')\nplt.tight_layout(); plt.show()"),
    md("## 3. Feature Engineering"),
    code("df['MA10']   = df['Price'].rolling(10).mean()\ndf['MA30']   = df['Price'].rolling(30).mean()\ndf['Std10']  = df['Price'].rolling(10).std()\ndf['Return'] = df['Price'].pct_change()\ndf['High5']  = df['Price'].rolling(5).max()\ndf['Low5']   = df['Price'].rolling(5).min()\ndf = df.dropna()\n\nfig, axes = plt.subplots(2, 1, figsize=(12, 6))\naxes[0].plot(df.index, df['Price'],  label='Price')\naxes[0].plot(df.index, df['MA10'],   label='MA10',  linestyle='--')\naxes[0].plot(df.index, df['MA30'],   label='MA30',  linestyle=':')\naxes[0].set_title('Price with Moving Averages'); axes[0].legend()\n\naxes[1].bar(df.index, df['Return'], alpha=0.6, color='tomato', width=1)\naxes[1].axhline(0, color='black', linewidth=0.5)\naxes[1].set_title('Daily Returns')\nplt.tight_layout(); plt.show()"),
    md("## 4. Building the Dataset"),
    code("FEAT_COLS = ['Price','MA10','MA30','Std10','Return','High5','Low5']\n\n# Scale all features to [0,1]\nfeat_scaler  = MinMaxScaler()\nprice_scaler = MinMaxScaler()\nscaled     = feat_scaler.fit_transform(df[FEAT_COLS].values.astype(np.float32))\nprice_sc   = price_scaler.fit_transform(df[['Price']].values.astype(np.float32))\n\nLOOKBACK = 30\n\ndef make_windows(features, target, lookback):\n    X, y = [], []\n    for i in range(len(features) - lookback):\n        X.append(features[i:i+lookback])\n        y.append(target[i+lookback])\n    return np.array(X, np.float32), np.array(y, np.float32)\n\nX_all, y_all = make_windows(scaled, price_sc, LOOKBACK)\n\n# Chronological split — NEVER shuffle!\nsplit = int(0.8 * len(X_all))\nX_tr, X_va = X_all[:split], X_all[split:]\ny_tr, y_va = y_all[:split], y_all[split:]\nprint(f'Train: {X_tr.shape}, Val: {X_va.shape}')"),
    md("## 5. LSTM Model"),
    code("class StockLSTM(nn.Module):\n    def __init__(self, n_features, hidden=64, layers=2, dropout=0.2):\n        super().__init__()\n        self.lstm = nn.LSTM(n_features, hidden, layers,\n                            batch_first=True, dropout=dropout)\n        self.fc = nn.Sequential(\n            nn.Linear(hidden, 32), nn.ReLU(), nn.Linear(32, 1)\n        )\n    def forward(self, x):\n        out, _ = self.lstm(x)\n        return self.fc(out[:, -1, :])\n\nmodel = StockLSTM(len(FEAT_COLS)).to(device)\nprint(f'Parameters: {sum(p.numel() for p in model.parameters()):,}')"),
    code("X_tr_t = torch.tensor(X_tr).to(device); y_tr_t = torch.tensor(y_tr).to(device)\nX_va_t = torch.tensor(X_va).to(device); y_va_t = torch.tensor(y_va).to(device)\n\ntrain_dl = DataLoader(TensorDataset(X_tr_t, y_tr_t), batch_size=32, shuffle=True)\ncriterion = nn.MSELoss()\noptimizer = optim.Adam(model.parameters(), lr=5e-4, weight_decay=1e-5)\nscheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=10, factor=0.5)\n\ntrain_losses, val_losses = [], []\nbest_val = float('inf')\n\nfor epoch in range(80):\n    model.train()\n    ep_loss = 0\n    for Xb, yb in train_dl:\n        optimizer.zero_grad()\n        loss = criterion(model(Xb), yb)\n        loss.backward()\n        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n        optimizer.step()\n        ep_loss += loss.item()\n    tl = ep_loss / len(train_dl)\n\n    model.eval()\n    with torch.no_grad():\n        vl = criterion(model(X_va_t), y_va_t).item()\n    scheduler.step(vl)\n    train_losses.append(tl); val_losses.append(vl)\n\n    if vl < best_val:\n        best_val = vl\n        torch.save(model.state_dict(), 'best_lstm.pt')\n\n    if (epoch+1) % 20 == 0:\n        print(f'Epoch {epoch+1:3d} | Train={tl:.5f} | Val={vl:.5f}')"),
    code("model.load_state_dict(torch.load('best_lstm.pt', map_location=device))\nmodel.eval()\n\nwith torch.no_grad():\n    y_pred_sc = model(X_va_t).cpu().numpy()\n\ny_pred = price_scaler.inverse_transform(y_pred_sc)\ny_true = price_scaler.inverse_transform(y_va)\n\nmae  = mean_absolute_error(y_true, y_pred)\nrmse = np.sqrt(mean_squared_error(y_true, y_pred))\nmape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100\nprint(f'MAE={mae:.2f}   RMSE={rmse:.2f}   MAPE={mape:.2f}%')"),
    code("fig, axes = plt.subplots(2, 1, figsize=(13, 8))\naxes[0].plot(train_losses, label='Train'); axes[0].plot(val_losses, label='Val')\naxes[0].set_xlabel('Epoch'); axes[0].set_ylabel('MSE'); axes[0].set_title('Loss Curve')\naxes[0].legend()\n\naxes[1].plot(y_true,  label='Actual',     linewidth=1.5)\naxes[1].plot(y_pred,  label='Predicted',  linewidth=1.5, linestyle='--')\naxes[1].fill_between(range(len(y_true)),\n                      y_pred.ravel()-rmse, y_pred.ravel()+rmse,\n                      alpha=0.15, color='orange', label='±RMSE')\naxes[1].set_xlabel('Time Step'); axes[1].set_ylabel('Price ($)')\naxes[1].set_title(f'LSTM Forecast  |  MAE=${mae:.2f}  RMSE=${rmse:.2f}  MAPE={mape:.1f}%')\naxes[1].legend()\nplt.tight_layout(); plt.show()"),
    md("## 6. Directional Accuracy"),
    code("dir_pred = np.sign(y_pred[1:] - y_pred[:-1])\ndir_true = np.sign(y_true[1:] - y_true[:-1])\nda = (dir_pred == dir_true).mean()\nprint(f'Directional accuracy: {da:.2%}')\nprint('(A random guesser achieves 50%)')"),
    md("## 7. Critical Assessment\n\n### What This Model Does Well\n- Captures short-term momentum from moving averages\n- Learns smooth trends in normalised data\n\n### What It Cannot Do\n- Predict reversals caused by breaking news\n- Generalise to market regime changes\n- Beat a buy-and-hold strategy consistently\n\n### The Efficient Market Hypothesis\nIn a semi-strong efficient market, prices already reflect all publicly available information. If a simple LSTM could reliably profit, everyone would use it and the signal would disappear immediately.\n\n**Lesson**: low MAPE on historical data does not mean the model will be profitable on live trading."),
    md("## Exercises\n\n1. Try `LOOKBACK = [10, 20, 30, 60]`. Which gives the lowest validation RMSE?\n2. Add RSI (Relative Strength Index) as a feature. Does it improve accuracy?\n3. Compare GRU vs LSTM: parameters, training time, RMSE.\n4. Download real data with `yfinance` and apply the same pipeline to AAPL or BTC-USD.\n5. Build a simple trading strategy: buy when the model predicts a price increase. Calculate total return vs buy-and-hold.\n\n## Reflection Questions\n- Why must we never shuffle time series data before splitting?\n- A model trained on 2010–2020 data is deployed in 2020. What problems might arise?\n- If MAPE = 1% sounds great, why might this model still be useless for trading?\n\n---\n\n## Course Summary\n\nCongratulations on completing DCS 404!\n\n| Module | Topic |\n|--------|-------|\n| 01 | AI fundamentals: search, A*, Minimax |\n| 02-04 | NumPy, Pandas, Matplotlib |\n| 05 | Data preparation and feature engineering |\n| 06 | Linear regression and regularisation |\n| 07-11 | Classification: logistic, SVM, KNN, NB, trees, ensembles |\n| 12 | Text classification (20 Newsgroups) |\n| 13 | Model evaluation and selection |\n| 14 | Clustering: K-Means, hierarchical, DBSCAN |\n| 15-17 | Deep learning: foundations, PyTorch, CNN, LSTM |\n| 18 | Applied LSTM: stock price forecasting |\n\n**What next?**: Transformers & Attention, Reinforcement Learning, Graph Neural Networks, Generative Models (VAE, GAN, Diffusion Models)"),
])

print("\n=== Part 2: Notebooks 10-18 generated successfully! ===")
